FROM node:20

WORKDIR /app

# Fix for git dependency issues (Permission denied publickey)
RUN git config --global url."https://github.com/".insteadOf "git@github.com:"
RUN git config --global url."https://".insteadOf "git://"

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --production

# Copy application source
COPY . .

# Set environment
ENV NODE_ENV=production
EXPOSE 3001

# Start application
CMD ["node", "src/app.js"]