

import React, { createContext, useState, ReactNode, useCallback, useEffect } from 'react';

// WORKAROUND: To bypass persistent module resolution errors, all translations are
// consolidated into a single static object within this file.
const translations = {
  en: {
    "betaBadge": "Beta",
    "currentPlan": "Current Plan",
    "currentPlanIs": "Your subscription to the {{planName}} is active.",
    "currentPlanUsage": "Current Plan Usage",
    "upgradeSubscription": "Upgrade Subscription",
    "staffUsage": "Staff Members",
    "servicesUsage": "Services",
    "locationsUsage": "Locations",
    "paymentProcessingError": "An error occurred during the payment process. Please try again.",
    "whatsappNotificationsEnabledText": "WhatsApp notifications are enabled.",
    "whatsappNotificationsDisabledText": "WhatsApp notifications are disabled.",
    "enableWhatsapp": "Enable WhatsApp",
    "disableWhatsapp": "Disable WhatsApp",
    "defaultPublicLang": "Default Public Page Language",
    "defaultPublicLangHelper": "This will be the initial language visitors see on your booking page.",
    "allowLanguageSelection": "Allow customers to select their language",
    "allowLanguageSelectionHelper": "If enabled, customers can choose their preferred language on the booking page. Otherwise, they will see only the default language.",
    "deletePlanInUseError": "Cannot delete this plan because it is currently assigned to one or more users. Please reassign users to a different plan before deleting.",
    "deleteDefaultPlanError": "Cannot delete the 'Standard' plan as it is the default plan for new users.",
    "whatsappHeader": "WhatsApp",
    "bookingsHeader": "Bookings",
    "emailMessagesHeader": "Emails Sent",
    "whatsappMessagesHeader": "WhatsApp Sent",
    "videoTutorial": "Video Tutorial",
    "proPlan": "Pro Plan",
    "businessPlan": "Business Plan",
    "upgradeToBusiness": "Upgrade to Business Plan",
    "upgradeAndUnlock": "Unlock more features and take your business to the next level.",
    "allProFeatures": "Everything in Pro, plus:",
    "featureUnlimitedLocations": "Unlimited Locations",
    "featureAllTemplates": "All Professional Templates",
    "featurePrioritySupport": "Priority Support",
    "businessPlanPriceLabel": "Business Plan Price (USD / month)",
    "savePlansButton": "Save Plan Settings",
    "langFrench": "French (FR)",
    "closedLabel": "Closed",
    "to": "to",
    "sunday": "Sunday",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "locationsLabel": "Locations",
    "viewPage": "View Page",
    "ourWork": "Our Work",
    "businessNotFound": "Business not found.",
    "loadBusinessError": "Failed to load business information.",
    "bookAppointment": "Book an Appointment",
    "yourNameLabel": "Your Name",
    "yourEmailLabel": "Your Email",
    "whatsappNumberLabel": "WhatsApp number",
    "countryCodePlaceholder": "+1",
    "phonePlaceholder": "555-123-4567",
    "notesHeader": "Notes",
    "notesPlaceholderPublic": "Any special requests or notes? (optional)",
    "selectStaffMember": "Select a Staff Member",
    "anyAvailable": "Any available",
    "chooseServices": "Choose a service(s)",
    "summaryTitle": "Summary",
    "totalLabel": "Total",
    "selectDateTime": "Select a Date & Time",
    "noTimesAvailable": "No times available on this date.",
    "requestAppointmentButton": "Request Appointment",
    "select": "Select",
    "selected": "Selected",
    "bookingConfirmed": "Booking Confirmed!",
    "bookingConfirmedSuccess": "Your appointment has been successfully booked. A confirmation email with details has been sent to you.",
    "bookAnotherService": "Book Another Service",
    "imagePreview": "Image Preview",
    "poweredBy": "Powered by",
    "otherServices": "Other Services",
    "calendarDays.su": "Su",
    "calendarDays.mo": "Mo",
    "calendarDays.tu": "Tu",
    "calendarDays.we": "We",
    "calendarDays.th": "Th",
    "calendarDays.fr": "Fr",
    "calendarDays.sa": "Sa",
    "staffNotWorkingError": "The selected staff member is not working at the chosen time. Please select another time.",
    "bookingFailedError": "Failed to create appointment. Please try again.",
    "selectedServicesNotFound": "Selected services not found.",
    "selectedStaffNotFound": "Selected staff member not found.",
    "noServicesForStaff": "No services available for this staff member.",
    "retrieveScheduleError": "Could not retrieve schedule. Please try again.",
    "limitedTimeOffer": "Limited-time free trial for the first {{count}} salons!",
    "whichIs": "which is",
    "durationInMinutesHelper": "Enter duration in minutes.",
    "durationLabel": "Duration",
    "emailLanguagesTitle": "Email Languages",
    "emailLanguagesDesc": "Select the languages for automated email confirmations and reminders.",
    "langEnglish": "English",
    "langPortuguese": "Português (Brasil)",
    "langArabic": "Arabic",
    "defaultLang": "(Default)",
    "saveLangSettings": "Save Language Settings",
    "showingBookingsCreatedOn": "Showing bookings created on {{date}}",
    "backToDashboard": "Back to Dashboard",
    "signInToAccount": "Sign in to your account",
    "emailAddressLabel": "Email address",
    "passwordLabel": "Password",
    "forgotPasswordLink": "Forgot Password?",
    "signInButton": "Sign in",
    "notAMember": "Not a member?",
    "signUpNowLink": "Sign up now",
    "yourBusinessSimplified": "Effortless Salon Management.",
    "invalidCredentialsError": "Invalid credentials. Please check your email and password.",
    "emailNotConfirmedError": "Please confirm your email address before logging in. Check your inbox for a confirmation link.",
    "createYourAccount": "Create your account",
    "fullNameLabel": "Full Name",
    "passwordLengthError": "Password should be at least 6 characters",
    "createAccountButton": "Create Account",
    "trialInfo": "Start your 14-day free trial. No credit card required.",
    "alreadyHaveAccount": "Already have an account?",
    "signInLink": "Sign in",
    "confirmYourEmail": "Confirm your email",
    "confirmationInstructions": "We've sent a confirmation link to your email address. Please check your inbox (and spam folder) to activate your account.",
    "alreadyConfirmed": "Already confirmed?",
    "signInHereLink": "Sign in here",
    "resetYourPassword": "Reset your password",
    "resetPasswordInstructions": "Enter your email address and we will send you a link to reset your password.",
    "sendResetLinkButton": "Send Reset Link",
    "passwordResetLinkSent": "Password reset link sent! Please check your email inbox.",
    "backToSignIn": "Back to Sign In",
    "rememberYourPassword": "Remember your password?",
    "setNewPassword": "Set a new password",
    "newPasswordLabel": "New Password",
    "confirmNewPasswordLabel": "Confirm New Password",
    "updatePasswordButton": "Update Password",
    "passwordsDoNotMatchError": "Passwords do not match.",
    "passwordUpdatedSuccess": "Password updated successfully! Redirecting to login...",
    "validatingResetLink": "Validating your reset link...",
    "linkErrorTitle": "Link Error",
    "invalidOrExpiredLink": "The password reset link is invalid or has expired. Please request a new link.",
    "requestNewLink": "Request a new link",
    "emailConfirmed": "Email Confirmed!",
    "accountActivated": "Your account has been successfully activated. You can now sign in to access your dashboard.",
    "goToSignIn": "Go to Sign In",
    "processingCancellation": "Processing your cancellation request...",
    "invalidCancellationLink": "Invalid cancellation link. No token provided.",
    "cancellationFailed": "Cancellation Failed",
    "bookingCanceled": "Booking Canceled",
    "bookingCanceledSuccess": "Your booking has been successfully canceled.",
    "sidebarDashboard": "Dashboard",
    "sidebarClients": "Clients",
    "sidebarRevenue": "Revenue",
    "sidebarSettings": "Settings",
    "sidebarTemplates": "Templates",
    "sidebarAutomation": "Automation",
    "sidebarSupport": "Support",
    "sidebarBilling": "Billing",
    "editProfile": "Edit Profile",
    "logout": "Logout",
    "trialDaysLeft": "You have {{days}} {{day_plural}} left in your free trial.",
    "day": "day",
    "days": "days",
    "upgradeNow": "Upgrade Now",
    "yourClients": "Your Clients",
    "exportToCSV": "Export to CSV",
    "allStaff": "All Staff",
    "allStatuses": "All Statuses",
    "approvedStatus": "Approved",
    "canceledStatus": "Canceled",
    "clearButton": "Clear",
    "customerHeader": "Customer",
    "serviceHeader": "Service",
    "staffHeader": "Staff",
    "dateTimeHeader": "Date & Time",
    "contactHeader": "Contact",
    "actionsHeader": "Actions",
    "noClientsFound": "No clients found for the selected filters.",
    "approveAction": "Approve",
    "cancelAction": "Cancel",
    "businessDetails": "Business Details",
    "businessDetailsDesc": "Update your business profile, photo, and working hours.",
    "businessNameLabel": "Business Name",
    "businessAddressLabel": "Business Address",
    "addressPlaceholder": "e.g., 123 Main St, Anytown, USA",
    "descriptionLabel": "Description",
    "businessPhotoLabel": "Business Photo",
    "imageUploadHelper": "JPG format, under 100KB.",
    "galleryImagesLabel": "Our Work / Gallery Images",
    "galleryImagesHelper": "Max 5 images. JPG format, under 100KB each. Recommended: 1200x800px.",
    "workingHoursStartLabel": "Working Hours Start",
    "workingHoursEndLabel": "Working Hours End",
    "closedDaysLabel": "Closed Days of the Week",
    "socialMediaLinks": "Social Media & Links",
    "websiteUrlLabel": "Website URL",
    "websitePlaceholder": "https://yourwebsite.com",
    "instagramUrlLabel": "Instagram URL",
    "instagramPlaceholder": "https://instagram.com/yourhandle",
    "facebookUrlLabel": "Facebook URL",
    "facebookPlaceholder": "https://facebook.com/yourpage",
    "whatsappContactLabel": "WhatsApp Contact Number",
    "whatsappContactPlaceholder": "+15551234567",
    "whatsappContactHelper": "Include country code, e.g., +1 for USA. This creates a direct WhatsApp link for your customers.",
    "saveChanges": "Save Changes",
    "calendarSettings": "Calendar Settings",
    "calendarSettingsDesc": "Configure booking rules like buffer times and advance notice.",
    "bookableInAdvanceLabel": "Bookable in advance (days)",
    "bookableInAdvanceHelper": "How many days in advance can customers book?",
    "minBookingNoticeLabel": "Minimum booking notice (hours)",
    "minBookingNoticeHelper": "Prevent last-minute bookings.",
    "bufferTimeLabel": "Buffer time between appointments (minutes)",
    "bufferTimeHelper": "Time for cleanup or prep between clients.",
    "timeSlotIntervalLabel": "Time Slot Interval",
    "timeSlotIntervalHelper": "The frequency of available appointment start times (e.g., every 30 minutes).",
    "saveCalendarSettings": "Save Calendar Settings",
    "manageStaff": "Manage Staff",
    "manageStaffDesc": "Add, edit, and remove staff members. Each staff member can have their own schedule.",
    "noStaffMembers": "No staff members added yet.",
    "addStaffMember": "Add Staff Member",
    "editAction": "Edit",
    "deleteAction": "Delete",
    "noServicesAssigned": "No services assigned",
    "manageServices": "Manage Services",
    "manageServicesDesc": "Define the services you offer to clients, including duration and price.",
    "noServicesYet": "No services added yet. Add one below to get started.",
    "addNewService": "Add New Service",
    "domains": "Domains",
    "yourSubdomain": "Your localDify Subdomain",
    "yourSubdomainDesc": "Set your unique public URL. This is the link you'll share with customers.",
    "bookingPageUrl": "Booking Page URL",
    "yourBusinessNamePlaceholder": "your-business-name",
    "saveLink": "Save Link",
    "copyLink": "Copy Link",
    "copied": "Copied!",
    "qrCode": "QR Code",
    "preview": "Preview",
    "connectYourDomain": "Connect Your Own Domain",
    "connectYourDomainDesc": "Point your own domain (e.g., `book.yourbusiness.com`) to your localDify page.",
    "customDomainPlaceholder": "book.yourbusiness.com",
    "cnameInstructions": "After saving, you will need to add a CNAME record in your domain provider's DNS settings.",
    "comingSoon": "Coming Soon",
    "welcomeTitle": "Welcome!",
    "welcomeDesc": "Start by setting up your business details to create services and get your public booking page.",
    "shareBookingPage": "Share Your Booking Page",
    "downloadQrCode": "Download QR Code",
    "profileInformation": "Profile Information",
    "removePhoto": "Remove Photo",
    "saveProfile": "Save Profile",
    "changePassword": "Change Password",
    "currentPasswordLabel": "Current Password",
    "goodMorning": "Good morning, {{name}}",
    "todayDate": "Today, {{date}}",
    "todaysAppointments": "Today's Appointments",
    "viewTodaysClients": "Click to view today's clients",
    "totalRevenue": "Total Revenue",
    "fromLast30Days": "from last 30 days",
    "totalAppointments": "Total Appointments",
    "newClients": "New Clients",
    "activityOverview": "Activity Overview",
    "activityOverviewDesc": "Visualize your business activity over time.",
    "appointmentsChart": "Appointments",
    "revenueChart": "Revenue",
    "newClientsChart": "New Clients",
    "last7Days": "Last 7 Days",
    "last14Days": "Last 14 Days",
    "last30Days": "Last 30 Days",
    "today": "Today",
    "yesterday": "Yesterday",
    "welcomeBack": "Welcome, {{name}}!",
    "setupBusinessPrompt": "It looks like you haven't set up your business yet.",
    "goToSettingsPrompt": "Go to Settings to Get Started",
    "revenue": "Revenue",
    "totalRevenueFiltered": "Total Revenue (filtered)",
    "fromAllAppointments": "From all approved appointments",
    "forSelectedDateRange": "For the selected date range",
    "revenueThisMonth": "Revenue This Month",
    "forMonth": "For {{month}}",
    "salesHistory": "Sales History",
    "appointmentDate": "Appointment Date",
    "amount": "Amount",
    "noSalesFound": "No sales found for the selected period.",
    "manageTemplate": "Manage Your Template",
    "manageTemplateDesc": "This is the theme for your public booking page. You can apply it to reset your page's appearance.",
    "templateAppliedSuccess": "Template \"{{templateName}}\" applied successfully!",
    "templateAppliedError": "Failed to apply template: {{error}}",
    "reapplyTheme": "Re-apply Classic Theme",
    "applyTheme": "Apply Classic Theme",
    "setupRequired": "Setup Required",
    "setupBusinessForTemplate": "Please set up your business details in the \"Settings\" tab before choosing a template.",
    "automationTitle": "Automation",
    "emailNotifications": "Email Notifications",
    "emailNotificationsDesc": "Send booking emails via the platform.",
    "emailNotificationsActive": "Email notifications are active.",
    "emailNotificationsInfo": "Booking confirmations and reminders are sent automatically. The \"From\" name will include your business, and replies will go directly to your login email.",
    "sendTestEmail": "Send a Test Email",
    "enterYourEmail": "Enter your email",
    "sendTest": "Send Test",
    "testEmailSent": "Test email sent to {{email}}!",
    "testEmailError": "Failed to send email: {{error}}",
    "whatsapp": "WhatsApp",
    "whatsappDesc": "Send booking messages via your Business Account.",
    "emailTemplates": "Email Templates",
    "emailTemplatesDesc": "Customize the emails sent to your customers. Click 'Save Templates' to apply your changes.",
    "templatesSavedSuccess": "Email templates saved successfully!",
    "templatesSavedError": "Failed to save templates: {{error}}",
    "saveTemplates": "Save Templates",
    "bookingConfirmation": "Booking Confirmation",
    "appointmentReminder": "Appointment Reminder",
    "emailSubject": "Email Subject",
    "emailBody": "Email Body",
    "availablePlaceholders": "Available Placeholders:",
    "supportCenter": "Support Center",
    "createNewTicket": "Create New Ticket",
    "yourSupportTickets": "Your Support Tickets",
    "yourSupportTicketsDesc": "View the history of your conversations with our support team.",
    "userHeader": "User",
    "businessHeader": "Business",
    "subjectHeader": "Subject",
    "lastUpdatedHeader": "Last Updated",
    "viewAction": "View",
    "noTicketsYet": "You haven't created any support tickets yet.",
    "backToTickets": "Back to all tickets",
    "openedOn": "Opened on {{date}}",
    "ticketClosedMessage": "This ticket is closed. To reopen it or for a new issue, please create a new ticket.",
    "typeYourReply": "Type your reply here...",
    "sendReply": "Send Reply",
    "createSupportTicketTitle": "Create New Support Ticket",
    "createSupportTicketDesc": "Our support team is here to help. Please describe your issue in detail.",
    "subjectLabel": "Subject",
    "subjectPlaceholder": "e.g., Issue with Gmail Integration",
    "messageLabel": "Message",
    "messagePlaceholder": "Please provide as much detail as possible...",
    "cancelButton": "Cancel",
    "submitTicketButton": "Submit Ticket",
    "billingSubscription": "Billing & Subscription",
    "proPlanActive": "Pro Plan Active",
    "proPlanActiveDesc": "Your subscription is active. Thank you for being a Pro member!",
    "activeBadge": "Active",
    "freeTrial": "Free Trial",
    "trialingBadge": "Trialing",
    "noActiveSubscription": "No Active Subscription",
    "noActiveSubscriptionDesc": "You are currently on the free plan. Upgrade to Pro to unlock all features.",
    "inactiveBadge": "Inactive",
    "upgradeToPro": "Upgrade to Pro",
    "paymentHistory": "Payment History",
    "descriptionHeader": "Description",
    "transactionIdHeader": "Transaction ID",
    "noPaymentHistory": "No payment history found.",
    "privacyPolicy": "Privacy Policy",
    "termsOfService": "Terms of Service",
    "adminPanel": "Admin Panel",
    "adminAccess": "Administration Access",
    "adminSignIn": "Administrator Sign In",
    "notAdmin": "Not an admin?",
    "goToUserLogin": "Go to user login",
    "adminDashboard": "Admin Dashboard",
    "totalUsers": "Total Users",
    "totalBusinesses": "Total Businesses",
    "totalBookings": "Total Bookings",
    "userManagement": "User Management",
    "userManagementDesc": "View, search, and manage all users.",
    "searchUsersPlaceholder": "Search by name, email, or business...",
    "subscriptionHeader": "Subscription",
    "trialEndsHeader": "Trial Ends",
    "joinedHeader": "Joined",
    "foundUsers": "Found {{count}} of {{total}} total users.",
    "revenueSubscriptions": "Revenue & Subscriptions",
    "mrr": "Monthly Recurring Revenue",
    "activeSubscriptions": "Active Subscriptions",
    "trialingUsers": "Trialing Users",
    "subscriberManagement": "Subscriber Management",
    "subscriberManagementDesc": "View and manage all user subscriptions.",
    "searchSubscribersPlaceholder": "Search by name, email, or business...",
    "paypalIdHeader": "PayPal Subscription ID",
    "foundSubscribers": "Found {{count}} of {{total}} total subscribers.",
    "systemSettings": "System Settings",
    "brevoSettings": "Email Provider (Brevo)",
    "brevoSettingsDesc": "Configure Brevo SMTP for sending all platform emails.",
    "brevoApiKeyLabel": "Brevo API Key",
    "brevoApiKeyPlaceholder": "xkeysib-...",
    "senderNameLabel": "Default Sender Name",
    "senderNamePlaceholder": "e.g., localDify",
    "senderNameHelper": "This name will appear in the 'From' field, like 'Business Name via [Sender Name]'.",
    "senderEmailLabel": "Default Sender Email",
    "senderEmailPlaceholder": "e.g., no-reply@yourdomain.com",
    "senderEmailHelper": "The email address all notifications will be sent from.",
    "saveEmailSettings": "Save Email Settings",
    "subscriptionSettings": "Subscription Settings",
    "subscriptionSettingsDesc": "Manage the monthly price for the Pro plan subscription.",
    "proPlanPriceLabel": "Pro Plan Price (USD / month)",
    "pricePlaceholder": "e.g., 19.00",
    "savePrice": "Save Price",
    "paymentIntegrations": "Payment Integrations",
    "paymentIntegrationsDesc": "Configure payment providers for user subscriptions.",
    "paypalConfig": "PayPal Configuration",
    "paypalConfigDesc1": "To enable PayPal subscriptions, you must set the `PAYPAL_CLIENT_ID` and `PAYPAL_CLIENT_SECRET` as secrets for your Supabase Edge Functions.",
    "paypalConfigDesc2": "This configuration is handled securely on the backend and cannot be set from this interface. Please refer to the `README.md` file for detailed instructions on how to set these environment variables in your Supabase project.",
    "configureInSupabase": "Configure in Supabase Secrets",
    "adminSupportTickets": "Support Tickets",
    "allTickets": "All Tickets",
    "allTicketsDesc": "Manage and respond to user support requests.",
    "searchTicketsPlaceholder": "Search tickets...",
    "openStatus": "Open",
    "inProgressStatus": "In Progress",
    "closedStatus": "Closed",
    "noTicketsFound": "No tickets match the current filters.",
    "ticketFrom": "From: {{name}} ({{email}})",
    "ticketBusiness": "Business: {{name}}",
    "ticketOpened": "Opened: {{date}}",
    "ticketClosedAdmin": "This ticket is closed. Change the status to \"Open\" or \"In Progress\" to reply.",
    "sendReplyButton": "Send Reply",
    "trialEndedTitle": "Your Free Trial Has Ended",
    "trialEndedDesc": "Subscribe to Pro to unlock all features and continue growing your business.",
    "loadingSubscription": "Loading Subscription Details...",
    "finalizingSubscription": "Finalizing Your Subscription...",
    "pleaseWait": "Please do not close this window.",
    "subscriptionSuccess": "Subscription Successful!",
    "welcomeToPro": "Welcome to Pro! Redirecting you to your dashboard...",
    "errorOccurred": "An Error Occurred",
    "tryAgain": "Try Again",
    "editServiceTitle": "Edit Service",
    "addServiceTitle": "Add New Service",
    "serviceNameLabel": "Service Name",
    "priceLabel": "Price",
    "serviceDescLabel": "Service Description",
    "serviceDescPlaceholder": "Describe the service...",
    "serviceImageLabel": "Service Image",
    "saveChangesButton": "Save Changes",
    "addServiceButton": "Add Service",
    "editStaffTitle": "Edit Staff Member",
    "addStaffTitle": "Add New Staff Member",
    "staffEmailLabel": "Email Address (Optional)",
    "photoLabel": "Photo",
    "servicesProvidedLabel": "Services Provided",
    "noServicesMessage": "No services created yet. Click \"Add New Service\" to start.",
    "addNewServiceButton": "Add New Service",
    "daysOffLabel": "Regular Days Off",
    "addStaffButton": "Add Staff",
    "addUserTitle": "Add New User",
    "editUserTitle": "Edit User",
    "passwordHelper": "Minimum 6 characters.",
    "roleLabel": "Role",
    "roleOwner": "Business Owner",
    "roleAdmin": "Admin",
    "subscriptionStatusLabel": "Subscription Status",
    "trialEndsAtLabel": "Trial Ends At",
    "extendTrial7": "+7 Days",
    "extendTrial14": "+14 Days",
    "extendTrial30": "+30 Days",
    "endTrialNow": "End Trial Now",
    "createUserButton": "Create User",
    "currency": "Currency",
    "currencyHelper": "Your prices and invoices will appear in the selected currency.",
    "currencyUpdateSuccess": "Currency updated successfully.",
    "currencyUpdateError": "Error updating currency.",
    "saving": "Saving",
    "chooseFile": "Choose File",
    "noFileChosen": "No file chosen",
    "minuteUnit": "min",
    "templateManagement": "Template Management",
    "templateManagementDesc": "Create, edit, and delete public page templates available to users.",
    "noTemplatesFound": "No templates found.",
    "addTemplate": "Add New Template",
    "editTemplate": "Edit Template",
    "deleteTemplateConfirm": "Are you sure you want to delete this template? This action cannot be undone.",
    "templateName": "Template Name",
    "templateDescription": "Description",
    "previewImageUrl": "Preview Image URL",
    "createTemplate": "Create Template",
    "templateError": "An error occurred: {{error}}",
    "htmlContent": "HTML Content",
    "cssContent": "CSS Content",
    "required": "Required",
    "optional": "Optional",
    "templateBookingAppDesc": "Your HTML must include {{booking_app}} where the booking form should appear.",
    "templateBusinessInfoDesc": "You can also use these placeholders to display business information:",
    "clickToCopy": "Click to copy",
    "notifications": "Notifications",
    "newBookingFrom": "New booking from {{name}}",
    "viewAllBookings": "View all bookings",
    "noNewNotifications": "No new notifications.",
    "todaysBookings": "Today's Bookings",
    "viewTodaysBookings": "Bookings created today",
    "topServices": "Top Services",
    "topServicesDesc": "Your most popular services by appointment count.",
    "noBookingData": "No booking data available to show top services yet.",
    "home.header.startFreeTrial": "Start Free Trial",
    "home.footer.copyright": "&copy; {{year}} localDify. All rights reserved.",
    "choosePlanTitle": "Choose Your Plan",
    "choosePlanDesc": "Your trial is still active. Upgrade now to keep your Pro features without interruption.",
    "perMonth": "per month",
    "proPlanFeature1": "Unlimited services",
    "proPlanFeature2": "Unlimited staff",
    "proPlanFeature3": "Unlimited booking",
    "proPlanFeature4": "One Template page",
    "proPlanFeature5": "One Location",
    "proPlanFeature6": "Email automation (300 emails/month)",
    "proPlanFeature7": "Dashboard for analytics",
    "businessPlanDesc": "For established businesses needing advanced features and multiple locations.",
    "businessPlanFeature1": "Everything in Pro Plan",
    "businessPlanFeature2": "All professional templates",
    "businessPlanFeature3": "Unlimited Locations",
    "businessPlanFeature4": "Unlimited Email/WhatsApp automation",
    "dangerZone": "Danger Zone",
    "deleteAccountTitle": "Delete This Account",
    "deleteAccountWarning": "Once deleted, all of your data will be permanently removed. This action cannot be undone.",
    "deleteAccountButton": "Delete Account",
    "areYouSure": "Are you absolutely sure?",
    "deleteConfirmationText": "This will permanently delete your account and all associated data, including your business, services, and bookings. To confirm, please type `DELETE` in the box below.",
    "typeDeleteToConfirm": "Type DELETE to confirm",
    "confirmDeletionButton": "I understand, delete my account",
    "accountDeletedSuccess": "Your account has been successfully deleted.",
    "brandCustomization": "Brand Customization",
    "brandColors": "Brand Colors",
    "primaryColor": "Primary Color",
    "secondaryColor": "Secondary Color",
    "coverImageLabel": "Background or Cover Image",
    "settingsPageDescription": "Manage your business profile, staff, services, and other settings.",
    "staffPageDescription": "Add, edit, and manage your staff members, their schedules, and assigned services.",
    "servicesPageDescription": "Define the services you offer to clients, including duration and price.",
    "searchStaffPlaceholder": "Search by name or email...",
    "deleteStaffConfirm": "Are you sure you want to delete this staff member? This action cannot be undone.",
    "noStaffFound": "No staff members found.",
    "workingHours": "Working Hours",
    "searchServicesPlaceholder": "Search by service name...",
    "deleteServiceConfirm": "Are you sure you want to delete this service? This action cannot be undone.",
    "noServicesFound": "No services found.",
    "price": "Price",
    "manageCategories": "Manage Categories",
    "newCategoryNamePlaceholder": "New category name...",
    "addButton": "Add",
    "editCategoryNameTitle": "Edit Category Name",
    "deleteCategoryConfirm": "Are you sure? Deleting a category will not delete its services; they will become uncategorized.",
    "categoryNameLabel": "Category Name",
    "locationsTab": "Locations",
    "manageLocationsTitle": "Manage Locations",
    "manageLocationsDesc": "Add and manage your business locations.",
    "addLocationButton": "Add Location",
    "deleteLocationConfirm": "Are you sure you want to delete this location? This cannot be undone.",
    "noLocationsMessage": "No locations added yet. Click 'Add Location' to get started.",
    "editLocationTitle": "Edit Location",
    "addLocationTitle": "Add New Location",
    "locationNameLabel": "Location Name",
    "locationNamePlaceholder": "e.g., Downtown Branch",
    "slugLabel": "URL Slug",
    "slugPlaceholder": "e.g., downtown-branch",
    "slugHelper": "A URL-friendly version of the name, used in the booking link. Only lowercase letters, numbers, and hyphens are allowed.",
    "allLocations": "All Locations",
    "selectLocation": "Select Location",
    "worksAtLocations": "Works at Locations",
    "availableAtLocations": "Available At Locations",
    "noLocationsConfiguredError": "This business has not configured any locations yet.",
    "welcomeToBusiness": "Welcome to {{name}}",
    "chooseLocationPrompt": "Please choose a location to continue.",
    "ourLocations": "Our Locations",
    "locationLabel": "Location",
    "opensAtLabel": "Opens At",
    "closesAtLabel": "Closes At",
    "subscriptionPlanLabel": "Subscription Plan",
    "planManagement": "Plan Management",
    "planManagementDesc": "Define and manage subscription plans for your users.",
    "addPlan": "Add New Plan",
    "editPlan": "Edit Plan",
    "deletePlanConfirm": "Are you sure you want to delete this plan? This action cannot be undone.",
    "planName": "Plan Name",
    "pricePerMonth": "Price (USD / month)",
    "staffLimit": "Staff Limit",
    "servicesLimit": "Services Limit",
    "locationsLimit": "Locations Limit",
    "emailQuota": "Email Quota (monthly)",
    "whatsappQuota": "WhatsApp Quota (monthly)",
    "unlimited": "Unlimited",
    "planActive": "Plan is Active",
    "planInactive": "Plan is Inactive",
    "activatePlan": "Activate Plan",
    "deactivatePlan": "Deactivate Plan",
    "limitReachedTitle": "You've Reached Your Limit for {{item}}",
    "limitReachedDesc": "You have reached the limit of {{limit}} {{item}} for your current plan. To add more, please upgrade your subscription.",
    "upgradePlan": "Upgrade Plan",
    "staffMembers": "Staff Members",
    "services": "Services",
    "locations": "Locations",
    "usageQuotas": "Usage Quotas",
    "usageQuotasDesc": "Track your monthly usage of automated messages.",
    "emailUsage": "Email Usage",
    "whatsappUsage": "WhatsApp Usage",
    "usedOf": "{{used}} / {{total}} used",
    "pages": "Pages",
    "pagesDesc": "Manage content for static pages like Home and Pricing."
  },
  fr: {
    "betaBadge": "Bêta",
    "currentPlan": "Plan Actuel",
    "currentPlanIs": "Votre abonnement au plan {{planName}} est actif.",
    "currentPlanUsage": "Utilisation du Plan Actuel",
    "upgradeSubscription": "Mettre à niveau l'abonnement",
    "staffUsage": "Membres du personnel",
    "servicesUsage": "Services",
    "locationsUsage": "Emplacements",
    "paymentProcessingError": "Une erreur est survenue lors du processus de paiement. Veuillez réessayer.",
    "whatsappNotificationsEnabledText": "Les notifications WhatsApp sont activées.",
    "whatsappNotificationsDisabledText": "Les notifications WhatsApp sont désactivées.",
    "enableWhatsapp": "Activer WhatsApp",
    "disableWhatsapp": "Désactiver WhatsApp",
    "defaultPublicLang": "Langue par Défaut de la Page Publique",
    "defaultPublicLangHelper": "Ce sera la langue initiale que les visiteurs verront sur votre page de réservation.",
    "allowLanguageSelection": "Permettre aux clients de sélectionner leur langue",
    "allowLanguageSelectionHelper": "Si activé, les clients peuvent choisir leur langue préférée sur la page de réservation. Sinon, ils ne verront que la langue par défaut.",
    "deletePlanInUseError": "Impossible de supprimer ce plan car il est actuellement attribué à un ou plusieurs utilisateurs. Veuillez réaffecter les utilisateurs à un autre plan avant de le supprimer.",
    "deleteDefaultPlanError": "Impossible de supprimer le plan 'Standard' car c'est le plan par défaut pour les nouveaux utilisateurs.",
    "whatsappHeader": "WhatsApp",
    "bookingsHeader": "Réservations",
    "emailMessagesHeader": "E-mails Envoyés",
    "whatsappMessagesHeader": "WhatsApp Envoyés",
    "videoTutorial": "Tutoriel Vidéo",
    "proPlan": "Plan Pro",
    "businessPlan": "Plan Business",
    "upgradeToBusiness": "Passer au Plan Business",
    "upgradeAndUnlock": "Débloquez plus de fonctionnalités et faites passer votre entreprise au niveau supérieur.",
    "allProFeatures": "Tout ce qui est inclus dans le Plan Pro, plus :",
    "featureUnlimitedLocations": "Emplacements illimités",
    "featureAllTemplates": "Tous les modèles professionnels",
    "featurePrioritySupport": "Support prioritaire",
    "businessPlanPriceLabel": "Prix du Plan Business (USD / mois)",
    "savePlansButton": "Enregistrer les paramètres du plan",
    "langFrench": "Français (FR)",
    "closedLabel": "Fermé",
    "to": "à",
    "sunday": "Dimanche",
    "monday": "Lundi",
    "tuesday": "Mardi",
    "wednesday": "Mercredi",
    "thursday": "Jeudi",
    "friday": "Vendredi",
    "saturday": "Samedi",
    "locationsLabel": "Emplacements",
    "viewPage": "Voir la page",
    "ourWork": "Nos réalisations",
    "businessNotFound": "Entreprise non trouvée.",
    "loadBusinessError": "Échec du chargement des informations de l'entreprise.",
    "bookAppointment": "Prendre un rendez-vous",
    "yourNameLabel": "Votre nom",
    "yourEmailLabel": "Votre e-mail",
    "whatsappNumberLabel": "Numéro WhatsApp",
    "countryCodePlaceholder": "+33",
    "phonePlaceholder": "6 12 34 56 78",
    "notesHeader": "Notes",
    "notesPlaceholderPublic": "Demandes spéciales ou notes ? (optionnel)",
    "selectStaffMember": "Sélectionner un membre du personnel",
    "anyAvailable": "N'importe qui",
    "chooseServices": "Choisir un ou plusieurs services",
    "summaryTitle": "Résumé",
    "totalLabel": "Total",
    "selectDateTime": "Sélectionner une date et une heure",
    "noTimesAvailable": "Aucun horaire disponible à cette date.",
    "requestAppointmentButton": "Demander un rendez-vous",
    "select": "Sélectionner",
    "selected": "Sélectionné",
    "bookingConfirmed": "Réservation Confirmée !",
    "bookingConfirmedSuccess": "Votre rendez-vous a été réservé avec succès. Un e-mail de confirmation avec les détails vous a été envoyé.",
    "bookAnotherService": "Réserver un autre service",
    "imagePreview": "Aperçu de l'image",
    "poweredBy": "Propulsé par",
    "otherServices": "Autres services",
    "calendarDays.su": "Di",
    "calendarDays.mo": "Lu",
    "calendarDays.tu": "Ma",
    "calendarDays.we": "Me",
    "calendarDays.th": "Je",
    "calendarDays.fr": "Ve",
    "calendarDays.sa": "Sa",
    "staffNotWorkingError": "Le membre du personnel sélectionné ne travaille pas à l'heure choisie. Veuillez sélectionner une autre heure.",
    "bookingFailedError": "Échec de la création du rendez-vous. Veuillez réessayer.",
    "selectedServicesNotFound": "Services sélectionnés non trouvés.",
    "selectedStaffNotFound": "Membre du personnel sélectionné non trouvé.",
    "noServicesForStaff": "Aucun service disponible pour ce membre du personnel.",
    "retrieveScheduleError": "Impossible de récupérer l'horaire. Veuillez réessayer.",
    "limitedTimeOffer": "Essai gratuit à durée limitée pour les {{count}} premiers salons !",
    "whichIs": "ce qui équivaut à",
    "durationInMinutesHelper": "Entrez la durée en minutes.",
    "durationLabel": "Durée",
    "emailLanguagesTitle": "Langues des e-mails",
    "emailLanguagesDesc": "Sélectionnez les langues pour les confirmations et rappels automatiques par e-mail.",
    "langEnglish": "Anglais",
    "langPortuguese": "Português (Brasil)",
    "langArabic": "Arabe",
    "defaultLang": "(Défaut)",
    "saveLangSettings": "Enregistrer les paramètres de langue",
    "showingBookingsCreatedOn": "Affichage des réservations créées le {{date}}",
    "backToDashboard": "Retour au tableau de bord",
    "signInToAccount": "Connectez-vous à votre compte",
    "emailAddressLabel": "Adresse e-mail",
    "passwordLabel": "Mot de passe",
    "forgotPasswordLink": "Mot de passe oublié ?",
    "signInButton": "Se connecter",
    "notAMember": "Pas encore membre ?",
    "signUpNowLink": "Inscrivez-vous maintenant",
    "yourBusinessSimplified": "La gestion de salon sans effort.",
    "invalidCredentialsError": "Identifiants invalides. Veuillez vérifier votre e-mail et votre mot de passe.",
    "emailNotConfirmedError": "Veuillez confirmer votre adresse e-mail avant de vous connecter. Vérifiez votre boîte de réception pour un lien de confirmation.",
    "createYourAccount": "Créez votre compte",
    "fullNameLabel": "Nom complet",
    "passwordLengthError": "Le mot de passe doit comporter au moins 6 caractères",
    "createAccountButton": "Créer un compte",
    "trialInfo": "Commencez votre essai gratuit de 14 jours. Aucune carte de crédit requise.",
    "alreadyHaveAccount": "Vous avez déjà un compte ?",
    "signInLink": "Se connecter",
    "confirmYourEmail": "Confirmez votre e-mail",
    "confirmationInstructions": "Nous avons envoyé un lien de confirmation à votre adresse e-mail. Veuillez vérifier votre boîte de réception (et votre dossier de spam) pour activer votre compte.",
    "alreadyConfirmed": "Déjà confirmé ?",
    "signInHereLink": "Connectez-vous ici",
    "resetYourPassword": "Réinitialisez votre mot de passe",
    "resetPasswordInstructions": "Entrez votre adresse e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    "sendResetLinkButton": "Envoyer le lien de réinitialisation",
    "passwordResetLinkSent": "Lien de réinitialisation du mot de passe envoyé ! Veuillez vérifier votre boîte de réception.",
    "backToSignIn": "Retour à la connexion",
    "rememberYourPassword": "Vous vous souvenez de votre mot de passe ?",
    "setNewPassword": "Définir un nouveau mot de passe",
    "newPasswordLabel": "Nouveau mot de passe",
    "confirmNewPasswordLabel": "Confirmer le nouveau mot de passe",
    "updatePasswordButton": "Mettre à jour le mot de passe",
    "passwordsDoNotMatchError": "Les mots de passe ne correspondent pas.",
    "passwordUpdatedSuccess": "Mot de passe mis à jour avec succès ! Redirection vers la connexion...",
    "validatingResetLink": "Validation de votre lien de réinitialisation...",
    "linkErrorTitle": "Erreur de lien",
    "invalidOrExpiredLink": "Le lien de réinitialisation du mot de passe est invalide ou a expiré. Veuillez demander un nouveau lien.",
    "requestNewLink": "Demander un nouveau lien",
    "emailConfirmed": "E-mail Confirmé !",
    "accountActivated": "Votre compte a été activé avec succès. Vous pouvez maintenant vous connecter pour accéder à votre tableau de bord.",
    "goToSignIn": "Aller à la connexion",
    "processingCancellation": "Traitement de votre demande d'annulation...",
    "invalidCancellationLink": "Lien d'annulation invalide. Aucun jeton fourni.",
    "cancellationFailed": "Échec de l'annulation",
    "bookingCanceled": "Réservation Annulée",
    "bookingCanceledSuccess": "Votre réservation a été annulée avec succès.",
    "sidebarDashboard": "Tableau de bord",
    "sidebarClients": "Clients",
    "sidebarRevenue": "Revenus",
    "sidebarSettings": "Paramètres",
    "sidebarTemplates": "Modèles",
    "sidebarAutomation": "Automatisation",
    "sidebarSupport": "Support",
    "sidebarBilling": "Facturation",
    "editProfile": "Modifier le profil",
    "logout": "Se déconnecter",
    "trialDaysLeft": "Il vous reste {{days}} {{day_plural}} dans votre essai gratuit.",
    "day": "jour",
    "days": "jours",
    "upgradeNow": "Mettre à niveau",
    "yourClients": "Vos Clients",
    "exportToCSV": "Exporter en CSV",
    "allStaff": "Tout le personnel",
    "allStatuses": "Tous les statuts",
    "approvedStatus": "Approuvé",
    "canceledStatus": "Annulé",
    "clearButton": "Effacer",
    "customerHeader": "Client",
    "serviceHeader": "Service",
    "staffHeader": "Personnel",
    "dateTimeHeader": "Date et Heure",
    "contactHeader": "Contact",
    "actionsHeader": "Actions",
    "noClientsFound": "Aucun client trouvé pour les filtres sélectionnés.",
    "approveAction": "Approuver",
    "cancelAction": "Annuler",
    "businessDetails": "Détails de l'entreprise",
    "businessDetailsDesc": "Mettez à jour le profil, la photo et les heures de travail de votre entreprise.",
    "businessNameLabel": "Nom de l'entreprise",
    "businessAddressLabel": "Adresse de l'entreprise",
    "addressPlaceholder": "ex: 123 Rue Principale, Paris, France",
    "descriptionLabel": "Description",
    "businessPhotoLabel": "Photo de l'entreprise",
    "imageUploadHelper": "Format JPG, moins de 100 Ko.",
    "galleryImagesLabel": "Nos Réalisations / Galerie d'images",
    "galleryImagesHelper": "Max 5 images. Format JPG, moins de 100 Ko chacune. Recommandé : 1200x800px.",
    "workingHoursStartLabel": "Début des heures de travail",
    "workingHoursEndLabel": "Fin des heures de travail",
    "closedDaysLabel": "Jours de fermeture de la semaine",
    "socialMediaLinks": "Réseaux Sociaux et Liens",
    "websiteUrlLabel": "URL du site web",
    "websitePlaceholder": "https://votresiteweb.com",
    "instagramUrlLabel": "URL Instagram",
    "instagramPlaceholder": "https://instagram.com/votrepseudo",
    "facebookUrlLabel": "URL Facebook",
    "facebookPlaceholder": "https://facebook.com/votepage",
    "whatsappContactLabel": "Numéro de contact WhatsApp",
    "whatsappContactPlaceholder": "+33612345678",
    "whatsappContactHelper": "Inclure l'indicatif du pays, ex: +33 pour la France. Cela crée un lien WhatsApp direct pour vos clients.",
    "saveChanges": "Enregistrer les modifications",
    "calendarSettings": "Paramètres du calendrier",
    "calendarSettingsDesc": "Configurez les règles de réservation comme les temps tampons et le préavis.",
    "bookableInAdvanceLabel": "Réservable à l'avance (jours)",
    "bookableInAdvanceHelper": "Combien de jours à l'avance les clients peuvent-ils réserver ?",
    "minBookingNoticeLabel": "Préavis minimum de réservation (heures)",
    "minBookingNoticeHelper": "Empêcher les réservations de dernière minute.",
    "bufferTimeLabel": "Temps tampon entre les rendez-vous (minutes)",
    "bufferTimeHelper": "Temps pour le nettoyage ou la préparation entre les clients.",
    "timeSlotIntervalLabel": "Intervalle de créneaux horaires",
    "timeSlotIntervalHelper": "La fréquence des heures de début de rendez-vous disponibles (par ex. toutes les 30 minutes).",
    "saveCalendarSettings": "Enregistrer les paramètres du calendrier",
    "manageStaff": "Gérer le personnel",
    "manageStaffDesc": "Ajoutez, modifiez et supprimez des membres du personnel. Chaque membre peut avoir son propre horaire.",
    "noStaffMembers": "Aucun membre du personnel ajouté pour le moment.",
    "addStaffMember": "Ajouter un membre du personnel",
    "editAction": "Modifier",
    "deleteAction": "Supprimer",
    "noServicesAssigned": "Aucun service assigné",
    "manageServices": "Gérer les services",
    "manageServicesDesc": "Définissez les services que vous offrez aux clients, y compris la durée et le prix.",
    "noServicesYet": "Aucun service ajouté pour le moment. Ajoutez-en un ci-dessous pour commencer.",
    "addNewService": "Ajouter un nouveau service",
    "domains": "Domaines",
    "yourSubdomain": "Votre sous-domaine localDify",
    "yourSubdomainDesc": "Définissez votre URL publique unique. C'est le lien que vous partagerez avec les clients.",
    "bookingPageUrl": "URL de la page de réservation",
    "yourBusinessNamePlaceholder": "votre-nom-d-entreprise",
    "saveLink": "Enregistrer le lien",
    "copyLink": "Copier le lien",
    "copied": "Copié !",
    "qrCode": "Code QR",
    "preview": "Aperçu",
    "connectYourDomain": "Connectez votre propre domaine",
    "connectYourDomainDesc": "Pointez votre propre domaine (par ex. `reserver.votreentreprise.com`) vers votre page localDify.",
    "customDomainPlaceholder": "reserver.votreentreprise.com",
    "cnameInstructions": "Après avoir enregistré, vous devrez ajouter un enregistrement CNAME dans les paramètres DNS de votre fournisseur de domaine.",
    "comingSoon": "Bientôt disponible",
    "welcomeTitle": "Bienvenue !",
    "welcomeDesc": "Commencez par configurer les détails de votre entreprise pour créer des services et obtenir votre page de réservation publique.",
    "shareBookingPage": "Partagez votre page de réservation",
    "downloadQrCode": "Télécharger le code QR",
    "profileInformation": "Informations du profil",
    "removePhoto": "Supprimer la photo",
    "saveProfile": "Enregistrer le profil",
    "changePassword": "Changer le mot de passe",
    "currentPasswordLabel": "Mot de passe actuel",
    "goodMorning": "Bonjour, {{name}}",
    "todayDate": "Aujourd'hui, {{date}}",
    "todaysAppointments": "Rendez-vous du jour",
    "viewTodaysClients": "Cliquez pour voir les clients du jour",
    "totalRevenue": "Revenus totaux",
    "fromLast30Days": "des 30 derniers jours",
    "totalAppointments": "Rendez-vous totaux",
    "newClients": "Nouveaux clients",
    "activityOverview": "Aperçu de l'activité",
    "activityOverviewDesc": "Visualisez l'activité de votre entreprise au fil du temps.",
    "appointmentsChart": "Rendez-vous",
    "revenueChart": "Revenus",
    "newClientsChart": "Nouveaux clients",
    "last7Days": "7 derniers jours",
    "last14Days": "14 derniers jours",
    "last30Days": "30 derniers jours",
    "today": "Aujourd'hui",
    "yesterday": "Hier",
    "welcomeBack": "Bienvenue, {{name}} !",
    "setupBusinessPrompt": "Il semble que vous n'ayez pas encore configuré votre entreprise.",
    "goToSettingsPrompt": "Allez dans les paramètres pour commencer",
    "revenue": "Revenus",
    "totalRevenueFiltered": "Revenus totaux (filtrés)",
    "fromAllAppointments": "De tous les rendez-vous approuvés",
    "forSelectedDateRange": "Pour la période sélectionnée",
    "salesHistory": "Historique des ventes",
    "appointmentDate": "Date du rendez-vous",
    "amount": "Montant",
    "noSalesFound": "Aucune vente trouvée pour la période sélectionnée.",
    "manageTemplate": "Gérer votre modèle",
    "manageTemplateDesc": "Ceci est le thème de votre page de réservation publique. Vous pouvez l'appliquer pour réinitialiser l'apparence de votre page.",
    "templateAppliedSuccess": "Modèle \"{{templateName}}\" appliqué avec succès !",
    "templateAppliedError": "Échec de l'application du modèle : {{error}}",
    "reapplyTheme": "Réappliquer le thème",
    "applyTheme": "Appliquer le thème",
    "setupRequired": "Configuration requise",
    "setupBusinessForTemplate": "Veuillez configurer les détails de votre entreprise dans l'onglet \"Paramètres\" avant de choisir un modèle.",
    "automationTitle": "Automatisation",
    "emailNotifications": "Notifications par e-mail",
    "emailNotificationsDesc": "Envoyez des e-mails de réservation via la plateforme.",
    "emailNotificationsActive": "Les notifications par e-mail sont actives.",
    "emailNotificationsInfo": "Les confirmations et rappels de réservation sont envoyés automatiquement. Le nom de l'expéditeur inclura votre entreprise, et les réponses iront directement à votre e-mail de connexion.",
    "sendTestEmail": "Envoyer un e-mail de test",
    "enterYourEmail": "Entrez votre e-mail",
    "sendTest": "Envoyer le test",
    "testEmailSent": "E-mail de test envoyé à {{email}} !",
    "testEmailError": "Échec de l'envoi de l'e-mail : {{error}}",
    "whatsapp": "WhatsApp",
    "whatsappDesc": "Envoyez des messages de réservation via votre compte Business.",
    "emailTemplates": "Modèles d'e-mail",
    "emailTemplatesDesc": "Personnalisez les e-mails envoyés à vos clients. Cliquez sur 'Enregistrer les modèles' pour appliquer vos modifications.",
    "templatesSavedSuccess": "Modèles d'e-mail enregistrés avec succès !",
    "templatesSavedError": "Échec de l'enregistrement des modèles : {{error}}",
    "saveTemplates": "Enregistrer les modèles",
    "bookingConfirmation": "Confirmation de réservation",
    "appointmentReminder": "Rappel de rendez-vous",
    "emailSubject": "Sujet de l'e-mail",
    "emailBody": "Corps de l'e-mail",
    "availablePlaceholders": "Variables disponibles :",
    "supportCenter": "Centre de support",
    "createNewTicket": "Créer un nouveau ticket",
    "yourSupportTickets": "Vos tickets de support",
    "yourSupportTicketsDesc": "Consultez l'historique de vos conversations avec notre équipe de support.",
    "userHeader": "Utilisateur",
    "businessHeader": "Entreprise",
    "subjectHeader": "Sujet",
    "lastUpdatedHeader": "Dernière mise à jour",
    "viewAction": "Voir",
    "noTicketsYet": "Vous n'avez encore créé aucun ticket de support.",
    "backToTickets": "Retour à tous les tickets",
    "openedOn": "Ouvert le {{date}}",
    "ticketClosedMessage": "Ce ticket est fermé. Pour le rouvrir ou pour un nouveau problème, veuillez créer un nouveau ticket.",
    "typeYourReply": "Tapez votre réponse ici...",
    "sendReply": "Envoyer la réponse",
    "createSupportTicketTitle": "Créer un nouveau ticket de support",
    "createSupportTicketDesc": "Notre équipe de support est là pour vous aider. Veuillez décrire votre problème en détail.",
    "subjectLabel": "Sujet",
    "subjectPlaceholder": "ex: Problème avec l'intégration Gmail",
    "messageLabel": "Message",
    "messagePlaceholder": "Veuillez fournir autant de détails que possible...",
    "cancelButton": "Annuler",
    "submitTicketButton": "Soumettre le ticket",
    "billingSubscription": "Facturation et Abonnement",
    "proPlanActive": "Plan Pro Actif",
    "proPlanActiveDesc": "Votre abonnement est actif. Merci d'être un membre Pro !",
    "activeBadge": "Actif",
    "freeTrial": "Essai gratuit",
    "trialingBadge": "En essai",
    "noActiveSubscription": "Aucun abonnement actif",
    "noActiveSubscriptionDesc": "Vous êtes actuellement sur le plan gratuit. Passez à Pro pour débloquer toutes les fonctionnalités.",
    "inactiveBadge": "Inactif",
    "manageOnPayPalDesc": "Votre abonnement est géré via PayPal. Cliquez sur le bouton ci-dessous pour voir l'historique des paiements ou annuler votre abonnement.",
    "manageOnPayPal": "Gérer sur PayPal",
    "upgradeToPro": "Passer à Pro",
    "paymentHistory": "Historique des paiements",
    "descriptionHeader": "Description",
    "transactionIdHeader": "ID de transaction",
    "noPaymentHistory": "Aucun historique de paiement trouvé.",
    "privacyPolicy": "Politique de confidentialité",
    "termsOfService": "Conditions d'utilisation",
    "adminPanel": "Panneau d'administration",
    "adminAccess": "Accès administrateur",
    "adminSignIn": "Connexion administrateur",
    "notAdmin": "Pas un administrateur ?",
    "goToUserLogin": "Aller à la connexion utilisateur",
    "adminDashboard": "Tableau de bord Admin",
    "totalUsers": "Total des utilisateurs",
    "totalBusinesses": "Total des entreprises",
    "totalBookings": "Total des réservations",
    "userManagement": "Gestion des utilisateurs",
    "userManagementDesc": "Voir, rechercher et gérer tous les utilisateurs.",
    "searchUsersPlaceholder": "Rechercher par nom, e-mail ou entreprise...",
    "subscriptionHeader": "Abonnement",
    "trialEndsHeader": "Fin de l'essai",
    "joinedHeader": "Inscrit le",
    "foundUsers": "{{count}} sur {{total}} utilisateurs trouvés.",
    "revenueSubscriptions": "Revenus et Abonnements",
    "mrr": "Revenu Mensuel Récurrent",
    "activeSubscriptions": "Abonnements Actifs",
    "trialingUsers": "Utilisateurs en Essai",
    "subscriberManagement": "Gestion des Abonnés",
    "subscriberManagementDesc": "Voir et gérer tous les abonnements des utilisateurs.",
    "searchSubscribersPlaceholder": "Rechercher par nom, e-mail ou entreprise...",
    "paypalIdHeader": "ID d'abonnement PayPal",
    "foundSubscribers": "{{count}} sur {{total}} abonnés trouvés.",
    "systemSettings": "Paramètres du système",
    "brevoSettings": "Fournisseur d'e-mail (Brevo)",
    "brevoSettingsDesc": "Configurez Brevo SMTP pour l'envoi de tous les e-mails de la plateforme.",
    "brevoApiKeyLabel": "Clé API Brevo",
    "brevoApiKeyPlaceholder": "xkeysib-...",
    "senderNameLabel": "Nom de l'expéditeur par défaut",
    "senderNamePlaceholder": "ex: localDify",
    "senderNameHelper": "Ce nom apparaîtra dans le champ 'De', comme 'Nom de l'entreprise via [Nom de l'expéditeur]'.",
    "senderEmailLabel": "E-mail de l'expéditeur par défaut",
    "senderEmailPlaceholder": "ex: ne-pas-repondre@votredomaine.com",
    "senderEmailHelper": "L'adresse e-mail à partir de laquelle toutes les notifications seront envoyées.",
    "saveEmailSettings": "Enregistrer les paramètres d'e-mail",
    "subscriptionSettings": "Paramètres d'abonnement",
    "subscriptionSettingsDesc": "Gérez le prix mensuel de l'abonnement au plan Pro.",
    "proPlanPriceLabel": "Prix du plan Pro (USD / mois)",
    "pricePlaceholder": "ex: 19.00",
    "savePrice": "Enregistrer le prix",
    "paymentIntegrations": "Intégrations de paiement",
    "paymentIntegrationsDesc": "Configurez les fournisseurs de paiement pour les abonnements des utilisateurs.",
    "paypalConfig": "Configuration PayPal",
    "paypalConfigDesc1": "Pour activer les abonnements PayPal, vous devez définir `PAYPAL_CLIENT_ID` et `PAYPAL_CLIENT_SECRET` comme secrets pour vos Fonctions Edge Supabase.",
    "paypalConfigDesc2": "Cette configuration est gérée de manière sécurisée sur le backend et ne peut pas être définie à partir de cette interface. Veuillez vous référer au fichier `README.md` pour des instructions détaillées sur la façon de définir ces variables d'environnement dans votre projet Supabase.",
    "configureInSupabase": "Configurer dans les secrets Supabase",
    "adminSupportTickets": "Tickets de support",
    "allTickets": "Tous les tickets",
    "allTicketsDesc": "Gérez et répondez aux demandes de support des utilisateurs.",
    "searchTicketsPlaceholder": "Rechercher des tickets...",
    "openStatus": "Ouvert",
    "inProgressStatus": "En cours",
    "closedStatus": "Fermé",
    "noTicketsFound": "Aucun ticket ne correspond aux filtres actuels.",
    "ticketFrom": "De : {{name}} ({{email}})",
    "ticketBusiness": "Entreprise : {{name}}",
    "ticketOpened": "Ouvert le : {{date}}",
    "ticketClosedAdmin": "Ce ticket est fermé. Changez le statut en \"Ouvert\" ou \"En cours\" pour répondre.",
    "sendReplyButton": "Envoyer la réponse",
    "trialEndedTitle": "Votre Essai Gratuit est Terminé",
    "trialEndedDesc": "Abonnez-vous à Pro pour débloquer toutes les fonctionnalités et continuer à développer votre entreprise.",
    "loadingSubscription": "Chargement des détails de l'abonnement...",
    "finalizingSubscription": "Finalisation de votre abonnement...",
    "pleaseWait": "Veuillez ne pas fermer cette fenêtre.",
    "subscriptionSuccess": "Abonnement Réussi !",
    "welcomeToPro": "Bienvenue à Pro ! Redirection vers votre tableau de bord...",
    "errorOccurred": "Une Erreur est Survenue",
    "tryAgain": "Réessayer",
    "editServiceTitle": "Modifier le service",
    "addServiceTitle": "Ajouter un nouveau service",
    "serviceNameLabel": "Nom du service",
    "priceLabel": "Prix",
    "serviceDescLabel": "Description du service",
    "serviceDescPlaceholder": "Décrivez le service...",
    "serviceImageLabel": "Image du service",
    "saveChangesButton": "Enregistrer les modifications",
    "addServiceButton": "Ajouter le service",
    "editStaffTitle": "Modifier le membre du personnel",
    "addStaffTitle": "Ajouter un nouveau membre du personnel",
    "staffEmailLabel": "Adresse e-mail (Optionnel)",
    "photoLabel": "Photo",
    "servicesProvidedLabel": "Services fournis",
    "noServicesMessage": "Aucun service créé pour le moment. Cliquez sur \"Ajouter un nouveau service\" pour commencer.",
    "addNewServiceButton": "Ajouter un nouveau service",
    "daysOffLabel": "Jours de congé réguliers",
    "addStaffButton": "Ajouter un membre",
    "addUserTitle": "Ajouter un nouvel utilisateur",
    "editUserTitle": "Modifier l'utilisateur",
    "passwordHelper": "Minimum 6 caractères.",
    "roleLabel": "Rôle",
    "roleOwner": "Propriétaire d'entreprise",
    "roleAdmin": "Admin",
    "subscriptionStatusLabel": "Statut de l'abonnement",
    "trialEndsAtLabel": "Fin de l'essai le",
    "extendTrial7": "+7 Jours",
    "extendTrial14": "+14 Jours",
    "extendTrial30": "+30 Jours",
    "endTrialNow": "Terminer l'essai maintenant",
    "createUserButton": "Créer l'utilisateur",
    "currency": "Devise",
    "currencyHelper": "Vos prix et factures apparaîtront dans la devise sélectionnée.",
    "currencyUpdateSuccess": "Devise mise à jour avec succès.",
    "currencyUpdateError": "Erreur lors de la mise à jour de la devise.",
    "saving": "Enregistrement",
    "chooseFile": "Choisir un fichier",
    "noFileChosen": "Aucun fichier choisi",
    "minuteUnit": "min",
    "templateManagement": "Gestion des modèles",
    "templateManagementDesc": "Créez, modifiez et supprimez les modèles de page publique disponibles pour les utilisateurs.",
    "noTemplatesFound": "Aucun modèle trouvé.",
    "addTemplate": "Ajouter un nouveau modèle",
    "editTemplate": "Modifier le modèle",
    "deleteTemplateConfirm": "Êtes-vous sûr de vouloir supprimer ce modèle ? Cette action est irréversible.",
    "templateName": "Nom du modèle",
    "templateDescription": "Description",
    "previewImageUrl": "URL de l'image d'aperçu",
    "createTemplate": "Créer le modèle",
    "templateError": "Une erreur est survenue : {{error}}",
    "htmlContent": "Contenu HTML",
    "cssContent": "Contenu CSS",
    "required": "Requis",
    "optional": "Optionnel",
    "templateBookingAppDesc": "Votre HTML doit inclure {{booking_app}} là où le formulaire de réservation doit apparaître.",
    "templateBusinessInfoDesc": "Vous pouvez également utiliser ces variables pour afficher les informations de l'entreprise :",
    "clickToCopy": "Cliquer pour copier",
    "notifications": "Notifications",
    "newBookingFrom": "Nouvelle réservation de {{name}}",
    "viewAllBookings": "Voir toutes les réservations",
    "noNewNotifications": "Aucune nouvelle notification.",
    "todaysBookings": "Réservations du jour",
    "viewTodaysBookings": "Réservations créées aujourd'hui",
    "topServices": "Services populaires",
    "topServicesDesc": "Vos services les plus populaires par nombre de rendez-vous.",
    "noBookingData": "Aucune donnée de réservation disponible pour afficher les services populaires pour le moment.",
    "home.header.startFreeTrial": "Commencer l'essai gratuit",
    "home.footer.copyright": "&copy; {{year}} localDify. Tous droits réservés.",
    "choosePlanTitle": "Choisissez votre plan",
    "choosePlanDesc": "Votre essai est toujours actif. Mettez à niveau maintenant pour conserver vos fonctionnalités Pro sans interruption.",
    "perMonth": "par mois",
    "proPlanFeature1": "Services illimités",
    "proPlanFeature2": "Personnel illimité",
    "proPlanFeature3": "Réservations illimitées",
    "proPlanFeature4": "Une page de modèle",
    "proPlanFeature5": "Un emplacement",
    "proPlanFeature6": "Automatisation des e-mails (300 e-mails/mois)",
    "proPlanFeature7": "Tableau de bord pour les analyses",
    "businessPlanDesc": "Pour les entreprises établies nécessitant des fonctionnalités avancées et plusieurs emplacements.",
    "businessPlanFeature1": "Tout ce qui est inclus dans le plan Pro",
    "businessPlanFeature2": "Tous les modèles professionnels",
    "businessPlanFeature3": "Emplacements illimités",
    "businessPlanFeature4": "Automatisation illimitée des e-mails/WhatsApp",
    "dangerZone": "Zone de danger",
    "deleteAccountTitle": "Supprimer ce compte",
    "deleteAccountWarning": "Une fois supprimées, toutes vos données seront définitivement effacées. Cette action est irréversible.",
    "deleteAccountButton": "Supprimer le compte",
    "areYouSure": "Êtes-vous absolument sûr ?",
    "deleteConfirmationText": "Cela supprimera définitivement votre compte et toutes les données associées, y compris votre entreprise, vos services et vos réservations. Pour confirmer, veuillez taper `DELETE` dans la case ci-dessous.",
    "typeDeleteToConfirm": "Tapez DELETE pour confirmer",
    "confirmDeletionButton": "Je comprends, supprimer mon compte",
    "accountDeletedSuccess": "Votre compte a été supprimé avec succès.",
    "brandCustomization": "Personnalisation de la marque",
    "brandColors": "Couleurs de la marque",
    "primaryColor": "Couleur principale",
    "secondaryColor": "Couleur secondaire",
    "coverImageLabel": "Image de fond ou de couverture",
    "settingsPageDescription": "Gérez le profil de votre entreprise, le personnel, les services et d'autres paramètres.",
    "staffPageDescription": "Ajoutez, modifiez et gérez les membres de votre personnel, leurs horaires et les services assignés.",
    "servicesPageDescription": "Définissez les services que vous offrez aux clients, y compris la durée et le prix.",
    "searchStaffPlaceholder": "Rechercher par nom ou e-mail...",
    "deleteStaffConfirm": "Êtes-vous sûr de vouloir supprimer ce membre du personnel ? Cette action est irréversible.",
    "noStaffFound": "Aucun membre du personnel trouvé.",
    "workingHours": "Heures de travail",
    "searchServicesPlaceholder": "Rechercher par nom de service...",
    "deleteServiceConfirm": "Êtes-vous sûr de vouloir supprimer ce service ? Cette action est irréversible.",
    "noServicesFound": "Aucun service trouvé.",
    "price": "Prix",
    "manageCategories": "Gérer les catégories",
    "newCategoryNamePlaceholder": "Nom de la nouvelle catégorie...",
    "addButton": "Ajouter",
    "editCategoryNameTitle": "Modifier le nom de la catégorie",
    "deleteCategoryConfirm": "Êtes-vous sûr ? La suppression d'une catégorie ne supprimera pas ses services ; ils deviendront non catégorisés.",
    "categoryNameLabel": "Nom de la catégorie",
    "locationsTab": "Emplacements",
    "manageLocationsTitle": "Gérer les emplacements",
    "manageLocationsDesc": "Ajoutez et gérez les emplacements de votre entreprise.",
    "addLocationButton": "Ajouter un emplacement",
    "deleteLocationConfirm": "Êtes-vous sûr de vouloir supprimer cet emplacement ? Cette action est irréversible.",
    "noLocationsMessage": "Aucun emplacement ajouté pour le moment. Cliquez sur 'Ajouter un emplacement' pour commencer.",
    "editLocationTitle": "Modifier l'emplacement",
    "addLocationTitle": "Ajouter un nouvel emplacement",
    "locationNameLabel": "Nom de l'emplacement",
    "locationNamePlaceholder": "ex: Succursale Centre-ville",
    "slugLabel": "Slug de l'URL",
    "slugPlaceholder": "ex: succursale-centre-ville",
    "slugHelper": "Une version du nom conviviale pour les URL, utilisée dans le lien de réservation. Seules les lettres minuscules, les chiffres et les tirets sont autorisés.",
    "allLocations": "Tous les emplacements",
    "selectLocation": "Sélectionner un emplacement",
    "worksAtLocations": "Travaille aux emplacements",
    "availableAtLocations": "Disponible aux emplacements",
    "noLocationsConfiguredError": "Cette entreprise n'a pas encore configuré d'emplacements.",
    "welcomeToBusiness": "Bienvenue chez {{name}}",
    "chooseLocationPrompt": "Veuillez choisir un emplacement pour continuer.",
    "ourLocations": "Nos emplacements",
    "locationLabel": "Emplacement",
    "opensAtLabel": "Ouvre à",
    "closesAtLabel": "Ferme à",
    "subscriptionPlanLabel": "Plan d'abonnement",
    "planManagement": "Gestion des plans",
    "planManagementDesc": "Définissez et gérez les plans d'abonnement pour vos utilisateurs.",
    "addPlan": "Ajouter un nouveau plan",
    "editPlan": "Modifier le plan",
    "deletePlanConfirm": "Êtes-vous sûr de vouloir supprimer ce plan ? Cette action est irréversible.",
    "planName": "Nom du plan",
    "pricePerMonth": "Prix (USD / mois)",
    "staffLimit": "Limite de personnel",
    "servicesLimit": "Limite de services",
    "locationsLimit": "Limite d'emplacements",
    "emailQuota": "Quota d'e-mails (mensuel)",
    "whatsappQuota": "Quota WhatsApp (mensuel)",
    "unlimited": "Illimité",
    "planActive": "Plan actif",
    "planInactive": "Plan inactif",
    "activatePlan": "Activer le plan",
    "deactivatePlan": "Désactiver le plan",
    "limitReachedTitle": "Vous avez atteint votre limite de {{item}}",
    "limitReachedDesc": "Vous avez atteint la limite de {{limit}} {{item}} pour votre plan actuel. Pour en ajouter plus, veuillez mettre à niveau votre abonnement.",
    "upgradePlan": "Mettre à niveau le plan",
    "staffMembers": "Membres du personnel",
    "services": "Services",
    "locations": "Emplacements",
    "usageQuotas": "Quotas d'utilisation",
    "usageQuotasDesc": "Suivez votre utilisation mensuelle des messages automatisés.",
    "emailUsage": "Utilisation des e-mails",
    "whatsappUsage": "Utilisation de WhatsApp",
    "usedOf": "{{used}} / {{total}} utilisés",
    "pages": "Pages",
    "pagesDesc": "Gérer le contenu des pages statiques comme l'accueil et les tarifs."
  },
  'pt-BR': {
    "currentPlan": "Plano Atual",
    "currentPlanUsage": "Uso do Plano Atual",
    "upgradeSubscription": "Atualizar Assinatura",
    "betaBadge": "Beta",
    "staffUsage": "Membros da Equipe",
    "servicesUsage": "Serviços",
    "locationsUsage": "Locais",
    "currentPlanIs": "Sua assinatura do plano {{planName}} está ativa.",
    "paymentProcessingError": "Ocorreu um erro durante o processo de pagamento. Por favor, tente novamente."
  },
  ar: {
    "currentPlan": "الخطة الحالية",
    "currentPlanUsage": "استخدام الخطة الحالية",
    "upgradeSubscription": "ترقية الاشتراك",
    "betaBadge": "تجريبي",
    "staffUsage": "الموظفين",
    "servicesUsage": "الخدمات",
    "locationsUsage": "المواقع",
    "whatsappHeader": "واتساب",
    "bookingsHeader": "الحجوزات",
    "emailMessagesHeader": "رسائل البريد الإلكتروني",
    "whatsappMessagesHeader": "رسائل واتساب",
    "whatsappNotificationsEnabledText": "إشعارات الواتساب مفعلة",
    "whatsappNotificationsDisabledText": "إشعارات الواتساب معطلة",
    "enableWhatsapp": "تفعيل الواتساب",
    "disableWhatsapp": "تعطيل الواتساب",
    "defaultPublicLang": "لغة الصفحة العامة الافتراضية",
    "defaultPublicLangHelper": "هذه ستكون اللغة الأولية التي سيراها الزوار على صفحة الحجز الخاصة بك.",
    "allowLanguageSelection": "السماح للعملاء باختيار لغتهم",
    "allowLanguageSelectionHelper": "إذا تم التفعيل، يمكن للعملاء اختيار لغتهم المفضلة على صفحة الحجز. وإلا، سيرون اللغة الافتراضية فقط.",
    "currentPlanIs": "اشتراكك في {{planName}} نشط.",
    "proPlan": "الخطة الاحترافية",
    "businessPlan": "خطة الأعمال",
    "upgradeToBusiness": "الترقية إلى خطة الأعمال",
    "upgradeAndUnlock": "افتح المزيد من الميزات وارتقِ بعملك إلى المستوى التالي.",
    "allProFeatures": "كل شيء في خطة برو، بالإضافة إلى:",
    "featureUnlimitedLocations": "مواقع غير محدودة",
    "featureAllTemplates": "جميع القوالب الاحترافية",
    "featurePrioritySupport": "دعم ذو أولوية",
    "businessPlanPriceLabel": "سعر خطة الأعمال (بالدولار الأمريكي / شهريًا)",
    "savePlansButton": "حفظ إعدادات الخطة",
    "langFrench": "الفرنسية (FR)",
    "closedLabel": "مغلق",
    "to": "إلى",
    "sunday": "الأحد",
    "monday": "الاثنين",
    "tuesday": "الثلاثاء",
    "wednesday": "الأربعاء",
    "thursday": "الخميس",
    "friday": "الجمعة",
    "saturday": "السبت",
    "locationsLabel": "المواقع",
    "viewPage": "عرض الصفحة",
    "ourWork": "أعمالنا",
    "businessNotFound": "العمل غير موجود.",
    "loadBusinessError": "فشل تحميل معلومات العمل.",
    "bookAppointment": "احجز موعدًا",
    "yourNameLabel": "اسمك",
    "yourEmailLabel": "بريدك الإلكتروني",
    "whatsappNumberLabel": "رقم الواتساب",
    "countryCodePlaceholder": "+966",
    "phonePlaceholder": "55-555-5555",
    "notesHeader": "ملاحظات",
    "notesPlaceholderPublic": "هل لديك أي طلبات أو ملاحظات خاصة؟ (اختياري)",
    "selectStaffMember": "اختر موظفًا",
    "anyAvailable": "أي موظف متاح",
    "chooseServices": "اختر خدمة (خدمات)",
    "summaryTitle": "ملخص",
    "totalLabel": "المجموع",
    "selectDateTime": "اختر تاريخًا ووقتًا",
    "noTimesAvailable": "لا توجد أوقات متاحة في هذا التاريخ.",
    "requestAppointmentButton": "طلب موعد",
    "select": "اختر",
    "selected": "محدد",
    "bookingConfirmed": "تم تأكيد الحجز!",
    "bookingConfirmedSuccess": "تم حجز موعدك بنجاح. تم إرسال بريد إلكتروني للتأكيد مع التفاصيل إليك.",
    "bookAnotherService": "حجز خدمة أخرى",
    "imagePreview": "معاينة الصورة",
    "poweredBy": "بدعم من",
    "otherServices": "خدمات أخرى",
    "calendarDays.su": "أحد",
    "calendarDays.mo": "إثن",
    "calendarDays.tu": "ثلا",
    "calendarDays.we": "أرب",
    "calendarDays.th": "خمي",
    "calendarDays.fr": "جمع",
    "calendarDays.sa": "سبت",
    "staffNotWorkingError": "الموظف المختار لا يعمل في الوقت المختار. يرجى اختيار وقت آخر.",
    "bookingFailedError": "فشل إنشاء الموعد. يرجى المحاولة مرة أخرى.",
    "selectedServicesNotFound": "الخدمات المحددة غير موجودة.",
    "selectedStaffNotFound": "الموظف المختار غير موجود.",
    "noServicesForStaff": "لا توجد خدمات متاحة لهذا الموظف.",
    "retrieveScheduleError": "تعذر استرداد الجدول. يرجى المحاولة مرة أخرى.",
    "limitedTimeOffer": "تجربة مجانية لفترة محدودة لأول {{count}} صالون!",
    "whichIs": "وهو ما يعادل",
    "durationInMinutesHelper": "أدخل المدة بالدقائق.",
    "durationLabel": "المدة",
    "emailLanguagesTitle": "لغات البريد الإلكتروني",
    "emailLanguagesDesc": "حدد اللغات لتأكيدات البريد الإلكتروني والتذكيرات التلقائية.",
    "langEnglish": "الإنجليزية",
    "langPortuguese": "البرتغالية (البرازيل)",
    "langArabic": "العربية",
    "defaultLang": "(الافتراضي)",
    "saveLangSettings": "حفظ إعدادات اللغة",
    "showingBookingsCreatedOn": "عرض الحجوزات التي تم إنشاؤها في {{date}}",
    "backToDashboard": "العودة إلى لوحة التحكم",
    "signInToAccount": "تسجيل الدخول إلى حسابك",
    "emailAddressLabel": "عنوان البريد الإلكتروني",
    "passwordLabel": "كلمة المرور",
    "forgotPasswordLink": "هل نسيت كلمة المرور؟",
    "signInButton": "تسجيل الدخول",
    "notAMember": "لست عضوا؟",
    "signUpNowLink": "سجل الآن",
    "yourBusinessSimplified": "عملك، مبسط.",
    "invalidCredentialsError": "بيانات الاعتماد غير صالحة. يرجى التحقق من بريدك الإلكتروني وكلمة المرور.",
    "emailNotConfirmedError": "يرجى تأكيد عنوان بريدك الإلكتروني قبل تسجيل الدخول. تحقق من صندوق الوارد الخاص بك للحصول على رابط التأكيد.",
    "createYourAccount": "أنشئ حسابك",
    "fullNameLabel": "الاسم الكامل",
    "passwordLengthError": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
    "createAccountButton": "إنشاء حساب",
    "trialInfo": "ابدأ تجربتك المجانية لمدة 14 يومًا. لا يلزم وجود بطاقة ائتمان.",
    "alreadyHaveAccount": "هل لديك حساب بالفعل؟",
    "signInLink": "تسجيل الدخول",
    "confirmYourEmail": "أكد بريدك الإلكتروني",
    "confirmationInstructions": "لقد أرسلنا رابط تأكيد إلى عنوان بريدك الإلكتروني. يرجى التحقق من صندوق الوارد الخاص بك (ومجلد الرسائل غير المرغوب فيها) لتفعيل حسابك.",
    "alreadyConfirmed": "هل أكدت بالفعل؟",
    "signInHereLink": "سجل الدخول هنا",
    "resetYourPassword": "إعادة تعيين كلمة المرور",
    "resetPasswordInstructions": "أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.",
    "sendResetLinkButton": "إرسال رابط إعادة التعيين",
    "passwordResetLinkSent": "تم إرسال رابط إعادة تعيين كلمة المرور! يرجى التحقق من صندوق الوارد الخاص بك.",
    "backToSignIn": "العودة إلى تسجيل الدخول",
    "rememberYourPassword": "هل تذكرت كلمة مرورك؟",
    "setNewPassword": "تعيين كلمة مرور جديدة",
    "newPasswordLabel": "كلمة المرور الجديدة",
    "confirmNewPasswordLabel": "تأكيد كلمة المرور الجديدة",
    "updatePasswordButton": "تحديث كلمة المرور",
    "passwordsDoNotMatchError": "كلمات المرور غير متطابقة.",
    "passwordUpdatedSuccess": "تم تحديث كلمة المرور بنجاح! جارٍ إعادة التوجيه إلى صفحة تسجيل الدخول...",
    "validatingResetLink": "جارٍ التحقق من رابط إعادة التعيين...",
    "linkErrorTitle": "خطأ في الرابط",
    "invalidOrExpiredLink": "رابط إعادة تعيين كلمة المرور غير صالح أو انتهت صلاحيته. يرجى طلب رابط جديد.",
    "requestNewLink": "طلب رابط جديد",
    "emailConfirmed": "تم تأكيد البريد الإلكتروني!",
    "accountActivated": "تم تفعيل حسابك بنجاح. يمكنك الآن تسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك.",
    "goToSignIn": "الذهاب إلى تسجيل الدخول",
    "processingCancellation": "جارٍ معالجة طلب الإلغاء...",
    "invalidCancellationLink": "رابط الإلغاء غير صالح. لم يتم توفير رمز مميز.",
    "cancellationFailed": "فشل الإلغاء",
    "bookingCanceled": "تم إلغاء الحجز",
    "bookingCanceledSuccess": "تم إلغاء حجزك بنجاح.",
    "sidebarDashboard": "لوحة التحكم",
    "sidebarClients": "العملاء",
    "sidebarRevenue": "الإيرادات",
    "sidebarSettings": "الإعدادات",
    "sidebarTemplates": "القوالب",
    "sidebarAutomation": "الأتمتة",
    "sidebarSupport": "الدعم",
    "sidebarBilling": "الفواتير",
    "editProfile": "تعديل الملف الشخصي",
    "logout": "تسجيل الخروج",
    "trialDaysLeft": "لديك {{days}} {{day_plural}} متبقية في الفترة التجريبية المجانية.",
    "day": "يوم",
    "days": "أيام",
    "upgradeNow": "الترقية الآن",
    "yourClients": "عملاؤك",
    "exportToCSV": "تصدير إلى CSV",
    "allStaff": "جميع الموظفين",
    "allStatuses": "جميع الحالات",
    "approvedStatus": "موافق عليه",
    "canceledStatus": "ملغى",
    "clearButton": "مسح",
    "customerHeader": "العميل",
    "serviceHeader": "الخدمة",
    "staffHeader": "الموظف",
    "dateTimeHeader": "التاريخ والوقت",
    "contactHeader": "الاتصال",
    "actionsHeader": "الإجراءات",
    "noClientsFound": "لم يتم العثور على عملاء للفلاتر المحددة.",
    "approveAction": "موافقة",
    "cancelAction": "إلغاء",
    "businessDetails": "تفاصيل العمل",
    "businessDetailsDesc": "تحديث ملف تعريف عملك وصورتك وساعات العمل.",
    "businessNameLabel": "اسم العمل",
    "businessAddressLabel": "عنوان العمل",
    "addressPlaceholder": "مثال: 123 شارع رئيسي، أي مدينة، الدولة",
    "descriptionLabel": "الوصف",
    "businessPhotoLabel": "صورة العمل",
    "imageUploadHelper": "تنسيق JPG، أقل من 100 كيلوبايت.",
    "galleryImagesLabel": "أعمالنا / صور المعرض",
    "galleryImagesHelper": "بحد أقصى 5 صور. تنسيق JPG، أقل من 100 كيلوبايت لكل منها. الأبعاد الموصى بها: 1200x800px.",
    "workingHoursStartLabel": "بداية ساعات العمل",
    "workingHoursEndLabel": "نهاية ساعات العمل",
    "closedDaysLabel": "أيام الإغلاق في الأسبوع",
    "socialMediaLinks": "وسائل التواصل الاجتماعي والروابط",
    "websiteUrlLabel": "رابط الموقع الإلكتروني",
    "websitePlaceholder": "https://yourwebsite.com",
    "instagramUrlLabel": "رابط إنستغرام",
    "instagramPlaceholder": "https://instagram.com/yourhandle",
    "facebookUrlLabel": "رابط فيسبوك",
    "facebookPlaceholder": "https://facebook.com/yourpage",
    "whatsappContactLabel": "رقم الاتصال بالواتساب",
    "whatsappContactPlaceholder": "+966555123456",
    "whatsappContactHelper": "أدخل رمز البلد، على سبيل المثال +966 للمملكة العربية السعودية. هذا ينشئ رابط واتساب مباشر لعملائك.",
    "saveChanges": "حفظ التغييرات",
    "calendarSettings": "إعدادات التقويم",
    "calendarSettingsDesc": "تكوين قواعد الحجز مثل أوقات الانتظار والإشعار المسبق.",
    "bookableInAdvanceLabel": "يمكن الحجز مقدمًا (بالأيام)",
    "bookableInAdvanceHelper": "كم يومًا مقدمًا يمكن للعملاء الحجز؟",
    "minBookingNoticeLabel": "الحد الأدنى للإشعار بالحجز (بالساعات)",
    "minBookingNoticeHelper": "منع الحجوزات في اللحظة الأخيرة.",
    "bufferTimeLabel": "وقت الانتظار بين المواعيد (بالدقائق)",
    "bufferTimeHelper": "وقت للتنظيف أو التحضير بين العملاء.",
    "timeSlotIntervalLabel": "فاصل زمني للوقت",
    "timeSlotIntervalHelper": "تكرار أوقات بدء المواعيد المتاحة (على سبيل المثال، كل 30 دقيقة).",
    "saveCalendarSettings": "حفظ إعدادات التقويم",
    "manageStaff": "إدارة الموظفين",
    "manageStaffDesc": "إضافة وتعديل وإزالة الموظفين. يمكن لكل موظف أن يكون له جدوله الخاص.",
    "noStaffMembers": "لم تتم إضافة أي موظفين بعد.",
    "addStaffMember": "إضافة موظف",
    "editAction": "تعديل",
    "deleteAction": "حذف",
    "noServicesAssigned": "لم يتم تعيين أي خدمات",
    "manageServices": "إدارة الخدمات",
    "manageServicesDesc": "تحديد الخدمات التي تقدمها للعملاء، بما في ذلك المدة والسعر.",
    "noServicesYet": "لم تتم إضافة أي خدمات بعد. أضف واحدة أدناه للبدء.",
    "addNewService": "إضافة خدمة جديدة",
    "domains": "النطاقات",
    "yourSubdomain": "النطاق الفرعي الخاص بك على localDify",
    "yourSubdomainDesc": "قم بتعيين عنوان URL العام الفريد الخاص بك. هذا هو الرابط الذي ستشاركه مع العملاء.",
    "bookingPageUrl": "عنوان URL لصفحة الحجز",
    "yourBusinessNamePlaceholder": "your-business-name",
    "saveLink": "حفظ الرابط",
    "copyLink": "نسخ الرابط",
    "copied": "تم النسخ!",
    "qrCode": "رمز الاستجابة السريعة",
    "preview": "معاينة",
    "connectYourDomain": "ربط نطاقك الخاص",
    "connectYourDomainDesc": "قم بتوجيه نطاقك الخاص (على سبيل المثال، `book.yourbusiness.com`) إلى صفحة localDify الخاصة بك.",
    "customDomainPlaceholder": "book.yourbusiness.com",
    "cnameInstructions": "بعد الحفظ، ستحتاج إلى إضافة سجل CNAME في إعدادات DNS لمزود النطاق الخاص بك.",
    "comingSoon": "قريبًا",
    "welcomeTitle": "أهلاً بك!",
    "welcomeDesc": "ابدأ بإعداد تفاصيل عملك لإنشاء خدمات والحصول على صفحة الحجز العامة الخاصة بك.",
    "shareBookingPage": "شارك صفحة الحجز الخاصة بك",
    "downloadQrCode": "تنزيل رمز الاستجابة السريعة",
    "profileInformation": "معلومات الملف الشخصي",
    "removePhoto": "إزالة الصورة",
    "saveProfile": "حفظ الملف الشخصي",
    "changePassword": "تغيير كلمة المرور",
    "currentPasswordLabel": "كلمة المرور الحالية",
    "goodMorning": "صباح الخير، {{name}}",
    "todayDate": "اليوم، {{date}}",
    "todaysAppointments": "مواعيد اليوم",
    "viewTodaysClients": "انقر لعرض عملاء اليوم",
    "totalRevenue": "إجمالي الإيرادات",
    "fromLast30Days": "من آخر 30 يومًا",
    "totalAppointments": "إجمالي المواعيد",
    "newClients": "عملاء جدد",
    "activityOverview": "نظرة عامة على النشاط",
    "activityOverviewDesc": "تصور نشاط عملك بمرور الوقت.",
    "appointmentsChart": "المواعيد",
    "revenueChart": "الإيرادات",
    "newClientsChart": "العملاء الجدد",
    "last7Days": "آخر 7 أيام",
    "last14Days": "آخر 14 يومًا",
    "last30Days": "آخر 30 يومًا",
    "today": "اليوم",
    "yesterday": "أمس",
    "welcomeBack": "أهلاً بعودتك، {{name}}!",
    "setupBusinessPrompt": "يبدو أنك لم تقم بإعداد عملك بعد.",
    "goToSettingsPrompt": "اذهب إلى الإعدادات للبدء",
    "revenue": "الإيرادات",
    "totalRevenueFiltered": "إجمالي الإيرادات (مفلتر)",
    "fromAllAppointments": "من جميع المواعيد المعتمدة",
    "forSelectedDateRange": "للفترة الزمنية المحددة",
    "revenueThisMonth": "إيرادات هذا الشهر",
    "forMonth": "لشهر {{month}}",
    "salesHistory": "سجل المبيعات",
    "appointmentDate": "تاريخ الموعد",
    "amount": "المبلغ",
    "noSalesFound": "لم يتم العثور على مبيعات للفترة المحددة.",
    "manageTemplate": "إدارة القوالب الخاصة بك",
    "manageTemplateDesc": "اختر قالبًا لصفحة الحجز العامة الخاصة بك. سيؤدي تطبيق قالب إلى استبدال المظهر الحالي لصفحتك بالتصميم المحدد.",
    "templateAppliedSuccess": "تم تطبيق القالب '{{templateName}}' بنجاح!",
    "templateAppliedError": "فشل تطبيق القالب: {{error}}",
    "reapplyTheme": "إعادة تطبيق السمة",
    "applyTheme": "تطبيق السمة",
    "setupRequired": "الإعداد مطلوب",
    "setupBusinessForTemplate": "يرجى إعداد تفاصيل عملك في علامة التبويب 'الإعدادات' قبل اختيار قالب.",
    "automationTitle": "الأتمتة",
    "emailNotifications": "إشعارات البريد الإلكتروني",
    "emailNotificationsDesc": "إرسال رسائل بريد إلكتروني للحجز عبر المنصة.",
    "emailNotificationsActive": "إشعارات البريد الإلكتروني نشطة.",
    "emailNotificationsInfo": "يتم إرسال تأكيدات وتذكيرات الحجز تلقائيًا. سيشمل اسم 'من' عملك، وستذهب الردود مباشرة إلى بريدك الإلكتروني لتسجيل الدخول.",
    "sendTestEmail": "إرسال بريد إلكتروني تجريبي",
    "enterYourEmail": "أدخل بريدك الإلكتروني",
    "sendTest": "إرسال اختبار",
    "testEmailSent": "تم إرسال بريد إلكتروني تجريبي إلى {{email}}!",
    "testEmailError": "فشل إرسال البريد الإلكتروني: {{error}}",
    "whatsapp": "واتساب",
    "whatsappDesc": "إرسال رسائل حجز عبر حسابك التجاري.",
    "emailTemplates": "قوالب البريد الإلكتروني",
    "emailTemplatesDesc": "تخصيص رسائل البريد الإلكتروني المرسلة إلى عملائك. انقر فوق 'حفظ القوالب' لتطبيق تغييراتك.",
    "templatesSavedSuccess": "تم حفظ قوالب البريد الإلكتروني بنجاح!",
    "templatesSavedError": "فشل حفظ القوالب: {{error}}",
    "saveTemplates": "حفظ القوالب",
    "bookingConfirmation": "تأكيد الحجز",
    "appointmentReminder": "تذكير بالموعد",
    "emailSubject": "موضوع البريد الإلكتروني",
    "emailBody": "نص البريد الإلكتروني",
    "availablePlaceholders": "العناصر النائبة المتاحة:",
    "supportCenter": "مركز الدعم",
    "createNewTicket": "إنشاء تذكرة جديدة",
    "yourSupportTickets": "تذاكر الدعم الخاصة بك",
    "yourSupportTicketsDesc": "عرض سجل محادثاتك مع فريق الدعم لدينا.",
    "userHeader": "المستخدم",
    "businessHeader": "العمل",
    "subjectHeader": "الموضوع",
    "lastUpdatedHeader": "آخر تحديث",
    "viewAction": "عرض",
    "noTicketsYet": "لم تقم بإنشاء أي تذاكر دعم بعد.",
    "backToTickets": "العودة إلى جميع التذاكر",
    "openedOn": "افتتح في {{date}}",
    "ticketClosedMessage": "هذه التذكرة مغلقة. لإعادة فتحها أو لمشكلة جديدة، يرجى إنشاء تذكرة جديدة.",
    "typeYourReply": "اكتب ردك هنا...",
    "sendReply": "إرسال الرد",
    "createSupportTicketTitle": "إنشاء تذكرة دعم جديدة",
    "createSupportTicketDesc": "فريق الدعم لدينا هنا للمساعدة. يرجى وصف مشكلتك بالتفصيل.",
    "subjectLabel": "الموضوع",
    "subjectPlaceholder": "على سبيل المثال، مشكلة في تكامل Gmail",
    "messageLabel": "الرسالة",
    "messagePlaceholder": "يرجى تقديم أكبر قدر ممكن من التفاصيل...",
    "cancelButton": "إلغاء",
    "submitTicketButton": "إرسال التذكرة",
    "billingSubscription": "الفواتير والاشتراك",
    "proPlanActive": "خطة Pro نشطة",
    "proPlanActiveDesc": "اشتراكك نشط. شكرًا لكونك عضوًا في Pro!",
    "activeBadge": "نشط",
    "freeTrial": "تجربة مجانية",
    "trialingBadge": "في فترة تجريبية",
    "noActiveSubscription": "لا يوجد اشتراك نشط",
    "noActiveSubscriptionDesc": "أنت حاليًا على الخطة المجانية. قم بالترقية إلى Pro لفتح جميع الميزات.",
    "inactiveBadge": "غير نشط",
    "manageOnPayPalDesc": "تتم إدارة اشتراكك من خلال PayPal. انقر على الزر أدناه لعرض سجل الدفع أو إلغاء اشتراكك.",
    "manageOnPayPal": "الإدارة على PayPal",
    "upgradeToPro": "الترقية إلى Pro",
    "paymentHistory": "سجل الدفع",
    "descriptionHeader": "الوصف",
    "transactionIdHeader": "معرف المعاملة",
    "noPaymentHistory": "لم يتم العثور على سجل دفع.",
    "privacyPolicy": "سياسة الخصوصية",
    "termsOfService": "شروط الخدمة",
    "adminPanel": "لوحة الإدارة",
    "adminAccess": "وصول المسؤول",
    "adminSignIn": "تسجيل دخول المسؤول",
    "notAdmin": "لست مسؤولا؟",
    "goToUserLogin": "الذهاب إلى تسجيل دخول المستخدم",
    "adminDashboard": "لوحة تحكم المسؤول",
    "totalUsers": "إجمالي المستخدمين",
    "totalBusinesses": "إجمالي الأعمال",
    "totalBookings": "إجمالي الحجوزات",
    "userManagement": "إدارة المستخدمين",
    "userManagementDesc": "عرض جميع المستخدمين والبحث فيهم وإدارتهم.",
    "searchUsersPlaceholder": "البحث بالاسم أو البريد الإلكتروني أو العمل...",
    "subscriptionHeader": "الاشتراك",
    "trialEndsHeader": "انتهاء الفترة التجريبية",
    "joinedHeader": "انضم في",
    "foundUsers": "تم العثور على {{count}} من إجمالي {{total}} مستخدمين.",
    "revenueSubscriptions": "الإيرادات والاشتراكات",
    "mrr": "الإيرادات الشهرية المتكررة",
    "activeSubscriptions": "الاشتراكات النشطة",
    "trialingUsers": "المستخدمون في الفترة التجريبية",
    "subscriberManagement": "إدارة المشتركين",
    "subscriberManagementDesc": "عرض وإدارة جميع اشتراكات المستخدمين.",
    "searchSubscribersPlaceholder": "البحث بالاسم أو البريد الإلكتروني أو العمل...",
    "paypalIdHeader": "معرف اشتراك PayPal",
    "foundSubscribers": "تم العثور على {{count}} من إجمالي {{total}} مشتركين.",
    "systemSettings": "إعدادات النظام",
    "brevoSettings": "مزود البريد الإلكتروني (Brevo)",
    "brevoSettingsDesc": "تكوين Brevo SMTP لإرسال جميع رسائل البريد الإلكتروني للمنصة.",
    "brevoApiKeyLabel": "مفتاح API Brevo",
    "brevoApiKeyPlaceholder": "xkeysib-...",
    "senderNameLabel": "اسم المرسل الافتراضي",
    "senderNamePlaceholder": "على سبيل المثال، localDify",
    "senderNameHelper": "سيظهر هذا الاسم في حقل 'من'، مثل 'اسم العمل عبر [اسم المرسل]'.",
    "senderEmailLabel": "البريد الإلكتروني للمرسل الافتراضي",
    "senderEmailPlaceholder": "على سبيل المثال، no-reply@yourdomain.com",
    "senderEmailHelper": "عنوان البريد الإلكتروني الذي سيتم إرسال جميع الإشعارات منه.",
    "saveEmailSettings": "حفظ إعدادات البريد الإلكتروني",
    "subscriptionSettings": "إعدادات الاشتراك",
    "subscriptionSettingsDesc": "إدارة السعر الشهري لاشتراك خطة Pro.",
    "proPlanPriceLabel": "سعر خطة Pro (بالدولار الأمريكي / شهريًا)",
    "pricePlaceholder": "على سبيل المثال، 19.00",
    "savePrice": "حفظ السعر",
    "paymentIntegrations": "تكاملات الدفع",
    "paymentIntegrationsDesc": "تكوين موفري الدفع لاشتراكات المستخدمين.",
    "paypalConfig": "تكوين PayPal",
    "paypalConfigDesc1": "لتمكين اشتراكات PayPal، يجب عليك تعيين `PAYPAL_CLIENT_ID` و `PAYPAL_CLIENT_SECRET` كأسرار لوظائف Supabase Edge الخاصة بك.",
    "paypalConfigDesc2": "تتم معالجة هذا التكوين بشكل آمن في الخلفية ولا يمكن تعيينه من هذه الواجهة. يرجى الرجوع إلى ملف `README.md` للحصول على إرشادات مفصلة حول كيفية تعيين متغيرات البيئة هذه في مشروع Supabase الخاص بك.",
    "configureInSupabase": "التكوين في أسرار Supabase",
    "adminSupportTickets": "تذاكر الدعم",
    "allTickets": "جميع التذاكر",
    "allTicketsDesc": "إدارة طلبات دعم المستخدمين والرد عليها.",
    "searchTicketsPlaceholder": "البحث في التذاكر...",
    "openStatus": "مفتوح",
    "inProgressStatus": "قيد التنفيذ",
    "closedStatus": "مغلق",
    "noTicketsFound": "لا توجد تذاكر تطابق المرشحات الحالية.",
    "ticketFrom": "من: {{name}} ({{email}})",
    "ticketBusiness": "العمل: {{name}}",
    "ticketOpened": "افتتح في: {{date}}",
    "ticketClosedAdmin": "هذه التذكرة مغلقة. قم بتغيير الحالة إلى 'مفتوح' أو 'قيد التنفيذ' للرد.",
    "sendReplyButton": "إرسال الرد",
    "trialEndedTitle": "انتهت فترة التجربة المجانية",
    "trialEndedDesc": "اشترك في Pro لفتح جميع الميزات ومواصلة تنمية عملك.",
    "loadingSubscription": "جارٍ تحميل تفاصيل الاشتراك...",
    "finalizingSubscription": "جارٍ إنهاء اشتراكك...",
    "pleaseWait": "يرجى عدم إغلاق هذه النافذة.",
    "subscriptionSuccess": "تم الاشتراك بنجاح!",
    "welcomeToPro": "أهلاً بك في Pro! جارٍ إعادة توجيهك إلى لوحة التحكم الخاصة بك...",
    "errorOccurred": "حدث خطأ",
    "tryAgain": "حاول مرة أخرى",
    "editServiceTitle": "تعديل الخدمة",
    "addServiceTitle": "إضافة خدمة جديدة",
    "serviceNameLabel": "اسم الخدمة",
    "priceLabel": "السعر",
    "serviceDescLabel": "وصف الخدمة",
    "serviceDescPlaceholder": "صف الخدمة...",
    "serviceImageLabel": "صورة الخدمة",
    "saveChangesButton": "حفظ التغييرات",
    "addServiceButton": "إضافة خدمة",
    "editStaffTitle": "تعديل الموظف",
    "addStaffTitle": "إضافة موظف جديد",
    "staffEmailLabel": "عنوان البريد الإلكتروني (اختياري)",
    "photoLabel": "الصورة",
    "servicesProvidedLabel": "الخدمات المقدمة",
    "noServicesMessage": "لم يتم إنشاء أي خدمات بعد. انقر فوق 'إضافة خدمة جديدة' للبدء.",
    "addNewServiceButton": "إضافة خدمة جديدة",
    "daysOffLabel": "أيام الإجازة العادية",
    "addStaffButton": "إضافة موظف",
    "addUserTitle": "إضافة مستخدم جديد",
    "editUserTitle": "تعديل المستخدم",
    "passwordHelper": "6 أحرف على الأقل.",
    "roleLabel": "الدور",
    "roleOwner": "صاحب العمل",
    "roleAdmin": "مسؤول",
    "subscriptionStatusLabel": "حالة الاشتراك",
    "trialEndsAtLabel": "تنتهي الفترة التجريبية في",
    "extendTrial7": "+7 أيام",
    "extendTrial14": "+14 يومًا",
    "extendTrial30": "+30 يومًا",
    "endTrialNow": "إنهاء الفترة التجريبية الآن",
    "createUserButton": "إنشاء مستخدم",
    "currency": "العملة",
    "currencyHelper": "ستظهر أسعارك وفواتيرك بالعملة المحددة.",
    "currencyUpdateSuccess": "تم تحديث العملة بنجاح.",
    "currencyUpdateError": "خطأ في تحديث العملة.",
    "saving": "جار الحفظ",
    "chooseFile": "اختر ملف",
    "noFileChosen": "لم يتم اختيار أي ملف",
    "minuteUnit": "دقيقة",
    "templateManagement": "إدارة القوالب",
    "templateManagementDesc": "إنشاء وتعديل وحذف قوالب الصفحة العامة المتاحة للمستخدمين.",
    "noTemplatesFound": "لم يتم العثور على قوالب.",
    "addTemplate": "إضافة قالب جديد",
    "editTemplate": "تعديل القالب",
    "deleteTemplateConfirm": "هل أنت متأكد من أنك تريد حذف هذا القالب؟ لا يمكن التراجع عن هذا الإجراء.",
    "templateName": "اسم القالب",
    "templateDescription": "الوصف",
    "previewImageUrl": "عنوان URL لصورة المعاينة",
    "createTemplate": "إنشاء قالب",
    "templateError": "حدث خطأ: {{error}}",
    "htmlContent": "محتوى HTML",
    "cssContent": "محتوى CSS",
    "required": "مطلوب",
    "optional": "اختياري",
    "templateBookingAppDesc": "يجب أن يتضمن HTML الخاص بك {{booking_app}} حيث يجب أن يظهر نموذج الحجز.",
    "templateBusinessInfoDesc": "يمكنك أيضًا استخدام هذه العناصر النائبة لعرض معلومات العمل:",
    "clickToCopy": "انقر للنسخ",
    "notifications": "الإشعارات",
    "newBookingFrom": "حجز جديد من {{name}}",
    "viewAllBookings": "عرض جميع الحجوزات",
    "noNewNotifications": "لا توجد إشعارات جديدة.",
    "todaysBookings": "حجوزات اليوم",
    "viewTodaysBookings": "الحجوزات التي تم إنشاؤها اليوم",
    "topServices": "أفضل الخدمات",
    "topServicesDesc": "خدماتك الأكثر شيوعًا حسب عدد المواعيد.",
    "noBookingData": "لا توجد بيانات حجز متاحة لعرض أفضل الخدمات بعد.",
    "home.header.startFreeTrial": "ابدأ الفترة التجريبية",
    "home.footer.copyright": "&copy; {{year}} localDify. جميع الحقوق محفوظة.",
    "choosePlanTitle": "اختر خطتك",
    "choosePlanDesc": "فترتك التجريبية لا تزال نشطة. قم بالترقية الآن للحفاظ على ميزات Pro الخاصة بك دون انقطاع.",
    "perMonth": "شهريًا",
    "proPlanFeature1": "خدمات غير محدودة",
    "proPlanFeature2": "عدد غير محدود من الموظفين",
    "proPlanFeature3": "حجوزات غير محدودة",
    "proPlanFeature4": "صفحة قالب واحدة",
    "proPlanFeature5": "موقع واحد",
    "proPlanFeature6": "أتمتة البريد الإلكتروني (300 بريد إلكتروني/شهر)",
    "proPlanFeature7": "لوحة تحكم للتحليلات",
    "businessPlanDesc": "للشركات القائمة التي تحتاج إلى ميزات متقدمة ومواقع متعددة.",
    "businessPlanFeature1": "كل شيء في خطة برو",
    "businessPlanFeature2": "جميع القوالب الاحترافية",
    "businessPlanFeature3": "مواقع غير محدودة",
    "businessPlanFeature4": "أتمتة غير محدودة للبريد الإلكتروني/واتساب",
    "dangerZone": "منطقة الخطر",
    "deleteAccountTitle": "حذف هذا الحساب",
    "deleteAccountWarning": "بمجرد الحذف، سيتم إزالة جميع بياناتك بشكل دائم. لا يمكن التراجع عن هذا الإجراء.",
    "deleteAccountButton": "حذف الحساب",
    "areYouSure": "هل أنت متأكد تمامًا؟",
    "deleteConfirmationText": "سيؤدي هذا إلى حذف حسابك وجميع البيانات المرتبطة به بشكل دائم، بما في ذلك عملك وخدماتك وحجوزاتك. للتأكيد، يرجى كتابة `DELETE` في المربع أدناه.",
    "typeDeleteToConfirm": "اكتب DELETE للتأكيد",
    "confirmDeletionButton": "أنا أفهم، احذف حسابي",
    "accountDeletedSuccess": "تم حذف حسابك بنجاح.",
    "brandCustomization": "تخصيص العلامة التجارية",
    "brandColors": "ألوان العلامة التجارية",
    "primaryColor": "اللون الأساسي",
    "secondaryColor": "اللون الثانوي",
    "coverImageLabel": "صورة الخلفية أو الغلاف",
    "settingsPageDescription": "إدارة ملف تعريف عملك والموظفين والخدمات والإعدادات الأخرى.",
    "staffPageDescription": "إضافة وتعديل وإدارة موظفيك وجداولهم والخدمات المعينة لهم.",
    "servicesPageDescription": "تحديد الخدمات التي تقدمها للعملاء، بما في ذلك المدة والسعر.",
    "searchStaffPlaceholder": "البحث بالاسم أو البريد الإلكتروني...",
    "deleteStaffConfirm": "هل أنت متأكد من أنك تريد حذف هذا الموظف؟ لا يمكن التراجع عن هذا الإجراء.",
    "noStaffFound": "لم يتم العثور على موظفين.",
    "workingHours": "ساعات العمل",
    "searchServicesPlaceholder": "البحث باسم الخدمة...",
    "deleteServiceConfirm": "هل أنت متأكد من أنك تريد حذف هذه الخدمة؟ لا يمكن التراجع عن هذا الإجراء.",
    "noServicesFound": "لم يتم العثور على خدمات.",
    "price": "السعر",
    "manageCategories": "إدارة الفئات",
    "newCategoryNamePlaceholder": "اسم الفئة الجديدة...",
    "addButton": "إضافة",
    "editCategoryNameTitle": "تعديل اسم الفئة",
    "deleteCategoryConfirm": "هل أنت متأكد؟ حذف فئة لن يحذف خدماتها؛ ستصبح غير مصنفة.",
    "categoryNameLabel": "اسم الفئة",
    "locationsTab": "المواقع",
    "manageLocationsTitle": "إدارة المواقع",
    "manageLocationsDesc": "أضف وأدر مواقع عملك.",
    "addLocationButton": "إضافة موقع",
    "deleteLocationConfirm": "هل أنت متأكد من أنك تريد حذف هذا الموقع؟ لا يمكن التراجع عن هذا الإجراء.",
    "noLocationsMessage": "لم تتم إضافة أي مواقع بعد. انقر فوق 'إضافة موقع' للبدء.",
    "editLocationTitle": "تعديل الموقع",
    "addLocationTitle": "إضافة موقع جديد",
    "locationNameLabel": "اسم الموقع",
    "locationNamePlaceholder": "مثال: فرع وسط المدينة",
    "slugLabel": "معرّف URL",
    "slugPlaceholder": "مثال: downtown-branch",
    "slugHelper": "إصدار صديق لعنوان URL للاسم، يُستخدم في رابط الحجز. يُسمح فقط بالأحرف الصغيرة والأرقام والشرطات.",
    "allLocations": "جميع المواقع",
    "selectLocation": "اختر موقعًا",
    "worksAtLocations": "يعمل في المواقع",
    "availableAtLocations": "متوفر في المواقع",
    "noLocationsConfiguredError": "لم يقم هذا النشاط التجاري بتكوين أي مواقع بعد.",
    "welcomeToBusiness": "أهلاً بك في {{name}}",
    "chooseLocationPrompt": "يرجى اختيار موقع للمتابعة.",
    "ourLocations": "مواقعنا",
    "locationLabel": "الموقع",
    "opensAtLabel": "يفتح في",
    "closesAtLabel": "يغلق في",
    "subscriptionPlanLabel": "خطة الاشتراك",
    "planManagement": "إدارة الخطة",
    "planManagementDesc": "تحديد وإدارة خطط الاشتراك للمستخدمين.",
    "addPlan": "إضافة خطة جديدة",
    "editPlan": "تعديل الخطة",
    "deletePlanConfirm": "هل أنت متأكد من أنك تريد حذف هذه الخطة؟ لا يمكن التراجع عن هذا الإجراء.",
    "planName": "اسم الخطة",
    "pricePerMonth": "السعر (بالدولار الأمريكي / شهريًا)",
    "staffLimit": "حد الموظفين",
    "servicesLimit": "حد الخدمات",
    "locationsLimit": "حد المواقع",
    "emailQuota": "حصة البريد الإلكتروني (شهريًا)",
    "whatsappQuota": "حصة الواتساب (شهريًا)",
    "unlimited": "غير محدود",
    "planActive": "الخطة نشطة",
    "planInactive": "الخطة غير نشطة",
    "activatePlan": "تفعيل الخطة",
    "deactivatePlan": "إلغاء تفعيل الخطة",
    "limitReachedTitle": "لقد وصلت إلى الحد الأقصى لـ {{item}}",
    "limitReachedDesc": "لقد وصلت إلى حد {{limit}} {{item}} لخطتك الحالية. لإضافة المزيد، يرجى ترقية اشتراكك.",
    "upgradePlan": "ترقية الخطة",
    "staffMembers": "الموظفين",
    "services": "الخدمات",
    "locations": "المواقع",
    "usageQuotas": "حصص الاستخدام",
    "usageQuotasDesc": "تتبع استخدامك الشهري للرسائل الآلية.",
    "emailUsage": "استخدام البريد الإلكتروني",
    "whatsappUsage": "استخدام الواتساب",
    "usedOf": "{{used}} / {{total}} مستخدم",
    "videoTutorial": "فيديو تعليمي",
    "pages": "الصفحات",
    "pagesDesc": "إدارة محتوى الصفحات الثابتة مثل الصفحة الرئيسية والتسعير."
  }
};

export type Language = 'en' | 'ar' | 'fr' | 'pt-BR';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, options?: { [key: string]: string | number }) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => { },
  t: (key) => key,
});

interface LanguageProviderProps {
  children: ReactNode;
  storageKey?: string;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children, storageKey = 'localdify-lang' }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const storedLang = localStorage.getItem(storageKey);
    if (storedLang && Object.keys(translations).includes(storedLang)) {
      return storedLang as Language;
    }
    return 'en';
  });

  useEffect(() => {
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
    }
  }, [language]);

  const handleSetLanguage = (lang: Language) => {
    if (Object.keys(translations).includes(lang)) {
      localStorage.setItem(storageKey, lang);
      setLanguage(lang);
    }
  };

  const t = useCallback((key: string, options?: { [key: string]: string | number }) => {
    const langSet = translations[language as keyof typeof translations] || translations.en;
    let translation = (langSet as any)[key] || (translations.en as any)[key] || key;

    if (options) {
      Object.keys(options).forEach(optionKey => {
        translation = String(translation).replace(`{{${optionKey}}}`, String(options[optionKey]));
      });
    }
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};